### ISSUE TITLE
Epic: MDM support

### ISSUE THREAD

**Issue by damonfeldman** [marklogic-community/marklogic-data-hub#126]
In my Master Data Management demo, integrating two data sources into a single master record, a few things were tricky.
- Having to have the original content.xqy create a single master record, and then have other plugins be aware of that single parent element and insert new records.
- Tracking provenance (not done in the demo yet). Nice to have standard provenance/date/master data tracked in all inputs.
- Having to have all content.xqy conform (work the same, produce the same main data, headers, triples, provenance)

It would be ideal if there was a set of MDM plugins or libraries that have different conceptual tasks, and perhaps only extract Headers, Triples and Provenance info, and have the framework assemble and track the Hub payload as hub:mdm-record containing the source data, and perhaps merging all the headers/triples together into one master record. Also nice to "retract" a source, support split/join after the fact.

Big topic, not sure what's needed.

┆Status: To Do

**Comment by jmakeig** [comment]
Is this something that can be generalized into a library or is it a set of patterns? I’d expect the merge/split logic and provenance tracking to be *very* implementation specific. (Otherwise, off-the-shelf MDM solutions would likely work better, cheaper.)

**Comment by damonfeldman** [comment]
MDM may be an imprecise or even grandiose term here. For "data integration" we do need to pull multiple pieces of data about an Entity into one place, track provenance, do fuzzy lookup of matches (is this an update to an existing Entity or a new Entity) and so on.

Merge is not too hard if we define a Master record as the union of source records with all headers and triples combined. Spit is always going to be manual and/or implementation specific, but having the automatic processing in the Hub can be combined with allowing people to layer on some merge/split assertions.

**Comment by jmakeig** [comment]
@damonfeldman,  I understand what you’re getting at. I just don’t see opportunities to generalize, other than orchestrating bulk transformation. The details of said transformation will be very use case-specific. I feel like I'm missing something.

**Comment by popzip** [comment]
I'll note this conversation for the smart mastering project (https://github.com/marklogic-community/smart-mastering-core)
