### ISSUE TITLE
Consider name and description for data hub framework and tooling

### ISSUE THREAD

**Issue by damonfeldman** [marklogic-community/marklogic-data-hub#175]
Definitions of "Data Hubs" are all over the place. Most are consistent with the kind of project addressed by this project similar to:

_Integrate, join, conform/clean, deduplicate and serve data, with validation, schema on read, schema on write all supported. Allow a hub-and-spoke model to a central repository, rather than point-to-point connections among multiple systems._ 

However others may define or redefine Data Hub to be something more, so we need to be clear about what this project is and is not for so that our notion of a "hub" is not confused with arbitrary definitions of data hubs from around the web, or people start to shift their thinking and expect a data hub to be something different.

We may
- alter the name to be more specific
- create a one-pager for both GitHub and elsewhere that defines Data Hub for our purposes

**Comment by paxtonhare** [comment]
@damonfeldman Is it safe to close this?

**Comment by damonfeldman** [comment]
Yes, I think so
