### ISSUE TITLE
Put min ML version in docs and error message

### ISSUE THREAD

**Issue by paxtonhare** [marklogic-community/marklogic-data-hub#229]
Error message being the one you get if you don't meet the minimum version.

**Comment by popzip** [comment]
@paxtonhare did this get completed? Is it addressed by @aebadirad recent work to deprecate ML8?

**Comment by popzip** [comment]
Min version of MarkLogic is in the documentation and it will error out (without specific version number) if ML8 used for example. Consider this complete.
