### ISSUE TITLE
Hub (un)install time on windows is horrible

### ISSUE THREAD

**Issue by paxtonhare** [marklogic-community/marklogic-data-hub#253]
not sure why

┆Status: To Do

**Comment by popzip** [comment]
@paxtonhare do you think still relevant? is it a bug?

**Comment by popzip** [comment]
@dmcassel you were using windows, right? Any signs that it is significantly worse than other OS?

**Comment by popzip** [comment]
@srinathgit i cannot assign to you, can you check on why?

also can you confirm whether this scenario - uninstall on windows - is in regression?

**Comment by srinathgit** [comment]
I am not sure why you can't assign the case to me. The tests (install and uninstall dhf) are running on Windows in Jenkins

**Comment by popzip** [comment]
Going to close since this is on an old version. If other performance/time issues please open new ticket.
