### ISSUE TITLE
Load files into the data hub schemas database

### ISSUE THREAD

**Issue by jkerr5** [marklogic-community/marklogic-data-hub#288]
The data hub currently supports loading files into the modules database but it should also be able to load files from a predefined directory into the data hub schemas database. This will be important for integrating with ML9 TDE as the templates are stored in the schemas database.

One minor note on TDE though is that a change to a template will cause an automatic redindex (assuming the reindexer is enabled) so the operational ramifications of that should be considered/discussed.

**Comment by grechaw** [comment]
Note that in the spring I implemented schemas (TDE and XSD) loading into ml-gradle

**Comment by paxtonhare** [comment]
If we assume that the end user continues to use our single schemas db:
data-hub-SCHEMAS then we can just have them put tde and xsd files in a
schemas dir and it will be picked up by gradle. But if the user goes off
the rails and adds additional schemas databases, perhaps one for staging
and one for final, then we might run into issues.

@jkerr5, any preference how we approach this?

**Comment by jmakeig** [comment]
I think we should back up a bit and be clear about what the objectives are in isolating staging and production into separate databases:

* Indexes: Tune the indexes for discovery of heterogenous data in staging, canonical entities in prod
* HA/DR: Probably less rigor in staging for failover and backups
* Workloads: Potentially perform ingest and harmonization on completely separate hosts to not take CPU or disk I/O from production queries/updates.

What else? Is having separate schemas databases part of that isolation story?  If not, we shouldn’t do anything to encourage it and/or actively discourage it.

**Comment by damonfeldman** [comment]
The physical separation into two databases rather than purely logical into collections is about administration, indexing and performance as Justin points out, so if a single, combined schema DB is just as fast and easy to administer as two (or easier) I think that should be fine.

**Comment by damonfeldman** [comment]
In terms of where the user puts TDE config/templates, though, I think they would best go in the "triples" plugin area rather than a combined schema directory. It's great that right now the entities and flows are largely self-contained, giving an entity-based view. If gradle likes things in one place and we put all schemas in one place (one DB) that's a factor, but the end-user experience should be about manging entities as self contained units I think. (Up to the point that entities are nested or linked to each other - cross-entitiy links obviously have to reference 2 or more entities).

**Comment by paxtonhare** [comment]
This works in the current release of the DHF. You put all schema docs into the user-config/schemas dir.

mlAppDeployer lets you add a collections.properties file in that same dir that puts the files into specific collections. It looks like:

```
name-of-file.xml=comma-delimited-list-of-collections
```
