### ISSUE TITLE
Control what runs in update mode to minimize locking

### ISSUE THREAD

**Issue by damonfeldman** [marklogic-community/marklogic-data-hub#300]
It's easy to get into trouble by running code in update mode when it should not. It would be good to add some configuration/best practice enforcement of read-only query. 

One option is to set up harmonize flows to run against staging in read-only mode (e.g. by checking the xdmp.timeStamp to be sure it exists, and error out otherwise, forcing writes to be via eval(), or based on some config.)

Another is to add a read-only vs. update setting on each flow. that could be confusing since a normal "read-only" flow might write to the final DB or write in some evals.

End goal is to avoid people doing large queries without understanding that they are locking or deadlocking because of some update code buried in a plugin or library.

**Comment by paxtonhare** [comment]
@damonfeldman I think we can close this one. All of the plugins except writer run in query mode. Sound good to you?

**Comment by damonfeldman** [comment]
yes
