### ISSUE TITLE
Getting Started tutorial shows a stack trace for step 8, sub-step 6

### ISSUE THREAD

**Issue by damonfeldman** [marklogic-community/marklogic-data-hub#316]
#### The issue

The screenshot in the tutorial has a stack trace rather than normal output

What behavior are you expecting?
To see typical execution, or a note saying why the stack trace is ok

┆Status: Eng Reviewed

**Comment by popzip** [comment]
I don't think this exists in latest tutorial, but please re-open if there is an issue with stack traces in the screenshots.
