### ISSUE TITLE
A trace is created with an invalid format

### ISSUE THREAD

**Issue by damonfeldman** [marklogic-community/marklogic-data-hub#397]
#### The issue

The trace GUI has one row saying "this trace has an invalid format"

The trace doc looks like

JSON Document as 
{
"trace": {
"format": "xml", 
"identifier": null, 
"flowType": "harmonize", 
"hasError": false, 
"collectorPlugin": {
"duration": "PT0.003951S", 
"output": [
"/InsuranceApplicaiton-David_Perez(1-pers).xml", 
"/InsuranceApplicaiton-Lita_Foxworth(1-pers).xml", 
"/InsuranceApplicaiton-Perez_Family(3-people).xml"
], 
"pluginModuleUri": "/entities/consumer/harmonize/insapp/collector/collector.xqy", 
"input": null
}, 
"created": "2017-05-02T17:37:00.195337-04:00", 
"traceId": "5641648933233875208"
}
}

Which Operating System are you using?
Mac OS X

Which version of MarkLogic are you using?
ML 9 nightly 02052017

Which version of the Data Hub Framework are you using?
1.1.2

#### The devil is in the details...

GUI capture is
![image](https://cloud.githubusercontent.com/assets/700633/25640692/8e5ccd3a-2f5e-11e7-883d-6bd722d50d6a.png)

┆Status: To Do

**Comment by popzip** [comment]
If you see this on 2.0.4+ please re open
