### ISSUE TITLE
Added Price, but didn't see it in the Product entity

### ISSUE THREAD

**Issue by dmcassel** [marklogic-community/marklogic-data-hub#408]
#### The issue

Short description of the problem: Added the price property in the Product entity editor, but it didn't show up in the Entities view, even after expanding the window. 

What behavior are you expecting? Entity view should show all properties (if the window is big enough). 

#### Tech details

Which Operating System are you using? Windows

Which version of MarkLogic are you using? 9.0-1.1

Which version of the Data Hub Framework are you using? v2.0.0-alpha.4

Is this a QuickStart UI bug? If so, which browser are you using? Chrome

┆Status: To Do

**Comment by popzip** [comment]
If you see this on 2.0.4+ please re-open. We recently fixed something related to overwriting entity properties.
