### ISSUE TITLE
Long collection names wrap (ugly)

### ISSUE THREAD

**Issue by dmcassel** [marklogic-community/marklogic-data-hub#409]
#### The issue

Short description of the problem: On the Browse Data tab of the Quick Start, long collection names wrap and look ugly. 

What behavior are you expecting? A beautiful, ascetically appealing view. 

#### Tech details

Which Operating System are you using? 

Which version of MarkLogic are you using? 9.0-1.1

Which version of the Data Hub Framework are you using? v2.0.0-alpha.4

Is this a QuickStart UI bug? If so, which browser are you using? Chrome

**Comment by dmcassel** [comment]
Here's a picture of the facet when looking at the final database. My browser window was 1495 pixels wide when I took that. 

![image](https://user-images.githubusercontent.com/701394/34008564-c577ec60-e0d3-11e7-8a13-795395fe4051.png)

@mhuang-ml dynamically changing size sounds like a good idea, within reason. I think it would also make sense to give a little more width to the facet.

**Comment by mhuang-ml** [comment]
@dmcassel, I've got logic to dynamically change the class based on the length of the facet name.  I currently only have two (2) classes, either the default class that has the font size be 14px or a different class that changes the size to be ".59vw".  I noticed that the truncated value is set to 40 characters, but for the screenshot below, then I changed the truncated value to be 30 characters.

Here's a screenshot of what I've currently implemented, I'm not sure if the size of the text is too small to read:
<img width="200" alt="screen shot 2018-01-15 at 10 09 46 pm" src="https://user-images.githubusercontent.com/16652599/34970301-a15da5b8-fa41-11e7-9290-44c19afe93b7.png">

The "test" collection is the default size that the ticket was originally opened against.  Any comments are greatly appreciated.

**Comment by dmcassel** [comment]
@mhuang-ml that looks like it will help a lot. If you hover over the facet value, can you see the full string?

**Comment by mhuang-ml** [comment]
@dmcassel, that's correct when you hover over the facet value, then the full string appears.  Here's a screenshot of the tooltip.

<img width="285" alt="screen shot 2018-01-17 at 10 05 41 pm" src="https://user-images.githubusercontent.com/16652599/35078917-a6e9b85e-fbd2-11e7-8874-86045fe9b7ff.png">
