### ISSUE TITLE
MLCP options: Add ability to select individual files

### ISSUE THREAD

**Issue by lsheth** [marklogic-community/marklogic-data-hub#413]
Currently you can only select folders in the MLCP UI.

Add the ability to choose files too.

edited by @paxtonhare from the original

**Comment by paxtonhare** [comment]
@lsheth can you elaborate on what you mean by "it doesn't allow me to correct the input folder path"?

Are you unable to type in a new path? Or are you unable to click on the .. button to navigate up?

**Comment by lsheth** [comment]
Yes I used the button to navigate up to the input folder path and then I was trying to type out the filename after he folder path because I just wanted one of the file ONLY to be processed from the folder in the specific input flow. I guess you can't pick the file using the navigation button nor you can type the filename in folder path. If you want only one file to be processed then just keep that file in the folder is probably the solution. Please let me know if there is a better way out.

**Comment by paxtonhare** [comment]
@lsheth ok thanks. I'm going to retitle this one to request the ability to choose a file.

**Comment by lsheth** [comment]
Perfect! Thank You Paxton
