### ISSUE TITLE
Test deploy against ssl enabled server

### ISSUE THREAD

**Issue by paxtonhare** [marklogic-community/marklogic-data-hub#417]
Verify if DHF will play well with SSL enabled servers.

This involves turning on SSL for the default MarkLogic app-servers (8000, 8001, 8002).

Looking for volunteer(s) to test this out.

**Comment by gku11ava** [comment]
Tested using Data Hub 1.1.3 on CentOS 6.8.

Created dummy certificate template in MarkLogic and assigned it to Admin, Manage and App-Services App-Servers. 

Specified mlAdminScheme=https and mlManageScheme=https as per ml-gradle SSL usage.

Initial run failed with PKIX error also encountered using ml-gradle with SSL so added the following custom code to build.properties:

/*
 *  Begin workaround for Manage server SSL 
 *
 *  This is a workaround to allow deployemts to work when SSL is
 *  enabled for the Manage port (8002)
 */
import org.apache.http.conn.ssl.TrustStrategy;
import java.security.cert.X509Certificate;

class SimpleStrategy implements TrustStrategy {
  public SimpleStrategy() {
  }

  public boolean isTrusted(X509Certificate[] chain, String authType) {
    return true;
  }
  
}

ext {
  def manageConfig = mlManageClient.getManageConfig()
  def strategy = new SimpleStrategy()
  def context = new org.apache.http.conn.ssl.SSLContextBuilder().loadTrustMaterial(null, strategy).build()
  def socketFactory = new org.apache.http.conn.ssl.SSLConnectionSocketFactory(context,
      org.apache.http.conn.ssl.SSLConnectionSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER)
  def scope = new org.apache.http.auth.AuthScope(mlAppConfig.getHost(), 8002, org.apache.http.auth.AuthScope.ANY_REALM)
  def credentials = new org.apache.http.auth.UsernamePasswordCredentials(manageConfig.getAdminUsername(), manageConfig.getAdminPassword())
  def provider = new org.apache.http.impl.client.BasicCredentialsProvider()
  provider.setCredentials(scope, credentials)
  def sslClient = org.apache.http.impl.client.HttpClients.custom().setDefaultCredentialsProvider(provider).setSSLSocketFactory(socketFactory).build()
  def restTemplate = mlManageClient.getRestTemplate()
  restTemplate.getRequestFactory().setHttpClient(sslClient)
  mlManageClient.setRestTemplate(restTemplate)
  mlManageClient.setAdminRestTemplate(restTemplate)
}

/*
 * End Manage Server SSL workaround
 */

This allows for successful configuration.   Note that the workaround is only needed if the manage server is using SSL.  

Deployment is mostly successful except for error deploying a javascript file:

Inserting module with URI: /trace-ui/vendor.64dbdd14c856e33bc8ed.bundle.js
com.marklogic.xcc.exceptions.ServerConnectionException: Malformed Response: <!DOCTYPE HTML PUBLIC '-//IETF//DTD HTML 2.0//EN'>
 [Session: user=admin, cb=data-hub-MODULES [ContentSource: user=admin, cb=data-hub-MODULES [provider: address=localhost/127.0.0.1:8000, pool=0/64]]]

If 8000 is not using SSL, this error is not observed.

While admin port is using SSL, configuration also seems to run a little slower with several tasks timing out and getting retried after exceeding 30 seconds waiting for MarkLogic restart.

Will test with CentOS7 and ML9 using 1.1.3 and 2.0.0-beta.1 next.

**Comment by paxtonhare** [comment]
Thank you, George!! This is awesome.

**Comment by paxtonhare** [comment]
Initial run failed with PKIX error

> also encountered using ml-gradle

with SSL so added the following custom code to build.properties

@gku11ava does this mean that ml-gradle has issues too?

**Comment by gku11ava** [comment]
Yes.    Looks like Rob is putting in a fix in ml-app-deployer.

https://github.com/marklogic-community/ml-gradle/issues/201

**Comment by paxtonhare** [comment]
I'm closing this because there is now a sample project for doing SSL.
