### ISSUE TITLE
Unable to ingest image (.png) documents using DHF Quick-Start application

### ISSUE THREAD

**Issue by lsheth** [marklogic-community/marklogic-data-hub#420]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:
Unable to ingest image (.png) documents using DHF Quick-Start application

What behavior are you expecting? Would like to ingest the image files using DHF quick-start application.

#### Tech details

Which Operating System are you using? Windows 7

Which version of MarkLogic are you using? 9.0-1.1

Which version of the Data Hub Framework are you using? 1.1.3

Is this a QuickStart UI bug? If so, which browser are you using? Chrome

#### The devil is in the details...
I am getting following error in job log:
13:33:03.624 [pool-1-thread-3] WARN  c.m.contentpump.TransformWriter - Failed document /image/aaron-brown-39.png
13:33:03.624 [pool-1-thread-3] WARN  c.m.contentpump.TransformWriter - <error:format-string xmlns:error="http://marklogic.com/xdmp/error" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">**You can't put a binary inside of an envelope. (CANT_RETURN_BINARY):**</error:format-string>

The MLCP command generated thru input-flow is as below:
mlcp.bat import -mode local -host localhost -port 8019 -username admin -password ***** -input_file_path C:\ML_DHF_Employee360\input\EmployeeImages -input_file_type "documents" -output_collections "images,input" -output_permissions "rest-reader,read,rest-writer,update" -output_uri_replace "/C:/ML_DHF_Employee360/input/EmployeeImages,'/image'" -document_type "binary" -transform_module "/com.marklogic.hub/mlcp-flow-transform.xqy" -transform_namespace "http://marklogic.com/data-hub/mlcp-flow-transform" -transform_param "entity=Employee,flow=images,flowType=input"

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by paxtonhare** [comment]
@lsheth do you want to create an envelope for the incoming png file(s)? Or do you just want to ingest binary data as-is?

**Comment by paxtonhare** [comment]
@lsheth did you see this example? https://github.com/marklogic-community/marklogic-data-hub/tree/1.0-master/examples/load-binaries

I'm inclined to close this issue. Any updates from you?
