### ISSUE TITLE
gradlew is generated without execute permission

### ISSUE THREAD

**Issue by damonfeldman** [marklogic-community/marklogic-data-hub#428]
#### The issue

When quickstart creates the gradle files, gradlew does not have execute permissions (mac/linux).

#### Tech details

Which Operating System are you using?
OSX

Which version of MarkLogic are you using?
9

Which version of the Data Hub Framework are you using?
2.x alpha
Is this a QuickStart UI bug? If so, which browser are you using?

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by jmakeig** [comment]
Why is it generated? Isn’t the normal workflow to check `gradew` into source control?

**Comment by paxtonhare** [comment]
@jmakeig I generate the gradlew artifacts as part of project initialization. We were seeing cases were people generated projects but had the incorrect version of gradle or no gradle installed. This allows anyone to run gradle commands as long as they have Java and internet.

**Comment by jmakeig** [comment]
But the whole point of gradew is that you *don’t* have to install anything. Maybe I’m misunderstanding the workflow here.
