### ISSUE TITLE
Error in documentation for the REST transform

### ISSUE THREAD

**Issue by tzejohn** [marklogic-community/marklogic-data-hub#433]
#### The issue

Short description of the problem:

In the advanced wiki documentation, the following is specified:

```
curl --anyauth --user user:password -T ./my-content -i \
  -H "Content-type: application/xml" \
  http://localhost:8010/v1/documents?uri=/shakespeare/plays/a_and_c.xml&transform=run-flow&trans:entity=YourEntityName&trans:flow=YourFlowName&trans:flowType=input&trans:jobId=someString
```
In the actual transform, it is expecting `job-id` instead of `jobId`. Also, `flowType` is hardcoded to *input*, and so is probably not needed in the example either, as it currently does not change anything.

**What behavior are you expecting?**

 So the example should probably read:

```
curl --anyauth --user user:password -T ./my-content -i \
  -H "Content-type: application/xml" \
  http://localhost:8010/v1/documents?uri=/shakespeare/plays/a_and_c.xml&transform=run-flow&trans:entity=YourEntityName&trans:flow=YourFlowName&trans:job-id=someString
```
#### Tech details
Which version of MarkLogic are you using?
8

Which version of the Data Hub Framework are you using?
1.1.3

**Comment by paxtonhare** [comment]
I updated the wiki to use job-id. I left in the flowType just in case.

Thanks @tzejohn !
