### ISSUE TITLE
Replica forests not created from quick-start

### ISSUE THREAD

**Issue by gduplantier** [marklogic-community/marklogic-data-hub#439]
#### The issue

Short description of the problem:
Replica forests are not being created from the quick-start UI when using the “mlDatabaseNamesAndReplicaCounts” gradle property.  They are created when using “gradle mlDeploy”

What behavior are you expecting?
I would expect the same behavior when deploying the data-hub from quick-start as gradle mlDeploy

#### Tech details

Which Operating System are you using? I tested this on RHEL 7 and MacOS

Which version of MarkLogic are you using? Latest 8.x version

Which version of the Data Hub Framework are you using? 1.3.3

Is this a QuickStart UI bug? If so, which browser are you using? Yes, but not a UI issue.

Debug output:
[myoutput.txt](https://github.com/marklogic/marklogic-data-hub/files/1081375/myoutput.txt)

**Comment by paxtonhare** [comment]
@gduplantier I feel like we discussed this offline and there was a simple fix for it. Do you recall?

**Comment by gduplantier** [comment]
The work around was simple, to use gradle instead of quick-start.  I'm not sure why the forest replica command is not working. From a quick glance at DataHub.java, seems like you should get it for free.

**Comment by paxtonhare** [comment]
was it because you put the mlDatabaseNamesAndReplicaCounts in your build.gradle vs gradle.properties?

**Comment by gduplantier** [comment]
No, I was putting it in gradle.properties.

**Comment by paxtonhare** [comment]
@gduplantier can you send me the hub project offline so I can test this? I think I have a fix.
