### ISSUE TITLE
Setting replica forest data path

### ISSUE THREAD

**Issue by gduplantier** [marklogic-community/marklogic-data-hub#441]
Short description of the problem:
How to set the replica forest data path without having an entirely customized forest configuration.  I would like to use mlDatabaseNamesAndReplicaCounts and have the replica forests use the same directory as the primary forests by default. Or, use a property for the replica forest path that I can set in gradle.properties.

This may be more of an ml-app-deployer issue or question. @rjrudin

**Comment by jmakeig** [comment]
This sounds mostly orthogonal to the Data Hub. Can you reproduce this issue in ml-gradle alone? If so, can you [create an issue in ml-gradle](https://github.com/marklogic-community/ml-gradle/issues/new)? Data Hub would inherit any changes there.

**Comment by rjrudin** [comment]
@gduplantier is correct - ml-app-deployer offers two options for creating forests - either you use a property and get "vanilla" replicas that can't be customized, or you have to spell out the config of every replica you want created. 

We can definitely support additional options in the middle, but I'm wondering - how would you want to configure those? I'm assuming this would be done via some mechanism (e.g. properties) other than JSON/XML payload files. I'm guessing we'd probably need a property per forest field that would then be applied to every replica payload that's generated. 

@jmakeig is right too - this sounds like it should be moved over to ml-app-deployer.

**Comment by gduplantier** [comment]
Moved to ml-app-deployer, [Issue 168](https://github.com/marklogic-community/ml-app-deployer/issues/168)
