### ISSUE TITLE
Input flow job (load-acme-tech) failing on 2.0.0-beta.1

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic-community/marklogic-data-hub#446]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:
My first input flow job for the Employee entity (load-acme-tech) is failing.

What behavior are you expecting?
The 2 documents should be loaded into staging

#### Tech details

Which Operating System are you using?
MacOS Sierra 10.12.5 (16F73)

Which version of MarkLogic are you using?
9.0-1.1

Which version of the Data Hub Framework are you using?
quick-start-2.0.0-beta.1.war

Is this a QuickStart UI bug? If so, which browser are you using?
Don't think so

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

```
11:23:35.152 [main] INFO  c.m.contentpump.LocalJobRunner - Content type: JSON
11:23:36.474 [main] INFO  c.marklogic.contentpump.ContentPump - Job name: local_1559598175_1
11:23:36.495 [main] INFO  c.m.c.FileAndDirectoryInputFormat - Total input paths to process : 2
11:23:37.505 [pool-1-thread-2] ERROR c.m.contentpump.MultithreadedMapper - Error running task: com/fasterxml/jackson/databind/node/ObjectNode
11:23:37.505 [pool-1-thread-3] ERROR c.m.contentpump.MultithreadedMapper - Error running task: com/fasterxml/jackson/databind/node/ObjectNode
11:23:37.507 [Thread-4] INFO  c.m.contentpump.LocalJobRunner -  completed 100%
11:23:37.512 [main] INFO  c.m.contentpump.LocalJobRunner - com.marklogic.mapreduce.MarkLogicCounter: 
11:23:37.513 [main] INFO  c.m.contentpump.LocalJobRunner - INPUT_RECORDS: 2
11:23:37.513 [main] INFO  c.m.contentpump.LocalJobRunner - OUTPUT_RECORDS: 2
11:23:37.513 [main] INFO  c.m.contentpump.LocalJobRunner - OUTPUT_RECORDS_COMMITTED: 0
11:23:37.513 [main] INFO  c.m.contentpump.LocalJobRunner - OUTPUT_RECORDS_FAILED: 0
11:23:37.513 [main] INFO  c.m.contentpump.LocalJobRunner - Total execution time: 1 sec
```

**Comment by damonfeldman** [comment]
Can you run this as an mlcp job from the command line to see if it is in the mlcp load job (data hub quickstart wraps and calls the mlcp libraries) or in the data hub itself? The GUI will output the mlcp command line to make this easy.

I see a funny error involving the JSON library (bad json?) but then also see "output_records=2" suggesting 2 inserts were sent to MarkLogic. Can you show the MarkLogic Error log for the 11:23:37 timeframe? just that second between 400-600 millis should do it. There may also be a failure in your flows.

**Comment by paxtonhare** [comment]
Please paste in the mlcp command that gets generated in the bottom box of the run flow page.

**Comment by sashamitrovich** [comment]
```
mlcp.sh import -mode local -host ea4-ml1 -port 8010 -username admin -password ***** -input_file_path /Users/smitrovi/GitHub/dhf/input/AcmeTech -input_file_type "documents" -output_collections "Employee,load-acme-tech,input" -output_permissions "rest-reader,read,rest-writer,update" -output_uri_replace "/Users/smitrovi/GitHub/dhf/input/AcmeTech,''" -document_type "json" -transform_module "/com.marklogic.hub/mlcp-flow-transform.xqy" -transform_namespace "http://marklogic.com/data-hub/mlcp-flow-transform" -transform_param "entity=Employee,flow=load-acme-tech,flowType=input"
```

**Comment by paxtonhare** [comment]
We have narrowed this down to a being unable to find a class:

java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/node/ObjectNode

It's an issue in mlcp-9.0.1

**Comment by sashamitrovich** [comment]
It seems to be an issue on my machine only but, for the love of god, I'm not able to pinpoint the cause :(

**Comment by paxtonhare** [comment]
@sashamitrovich filed a bug against mlcp. Closing the issue here.

**Comment by sashamitrovich** [comment]
So, it turns out mlcp (better said jam) was picking up an old XCC library from ~/Library/Java/Extensions. This folder exists only on macOS and should really never be used as the libraries put there will overwrite what you have in the classpath. That was exactly my issue. Thanks to @paxtonhare for sticking with me and helping me debug this nightmare.

More information here:
https://stackoverflow.com/questions/12880678/what-is-the-role-of-library-java-extensions-is-it-safe-to-add-or-remove-class
