### ISSUE TITLE
Ports 8010 and 8011 conflicting with Ops-Director

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic-community/marklogic-data-hub#447]
Ops-Director, a new ML9 feature (not released yet) is using ports 8010 and 8011 by default when installed.

**Comment by ndw** [comment]
Sigh. Ports are a limited resource. The user can choose different ports at install time with OpsDirector. We could also change the default ports if there's precedent for data hub to use 8010 and 8011.

**Comment by sashamitrovich** [comment]
We need an IPv6 for ports, it's getting crowded out there.

**Comment by paxtonhare** [comment]
@ndw Do you want to move or do you want me to move? 
An army of existing DHF installs are already running on 8010-8014.

A port change on my end would only affect future DHF installs as the existing base of users has already scaffolded their projects on these port.

However, any DHF user trying to install OpsDirector may run into port conflicts.
