### ISSUE TITLE
Changes to $options not persisting if set in headers or triples in Harmonization flow

### ISSUE THREAD

**Issue by smclean** [marklogic-community/marklogic-data-hub#448]
#### The issue

Short description of the problem: Data inserted to $options in content persist through rest of flow but updates to $options in either headers or triples are lost

What behavior are you expecting?
I would expect to be able to update $options in content, headers and triples and have them persist through the flow
#### Tech details

Which Operating System are you using?
Linux (RHEL)
Which version of MarkLogic are you using?
8 and 9
Which version of the Data Hub Framework are you using?
1.1.2
Is this a QuickStart UI bug? If so, which browser are you using?
No

**Comment by paxtonhare** [comment]
@smclean are you using xqy or sjs?

**Comment by smclean** [comment]
xquery

**Comment by paxtonhare** [comment]
@smclean I figured it was silly to ask, but wanted to be thorough. :)

**Comment by paxtonhare** [comment]
@smclean also, I just added a unit test for this. Works fine for 1.1.3 for xqy. But sjs is busted. Fix for sjs maps will go in 1.whatever-is-next
