### ISSUE TITLE
tutorial link is 404: https://marklogic.github.io/marklogic-data-hub/

### ISSUE THREAD

**Issue by mikrovvelle** [marklogic-community/marklogic-data-hub#449]
The address for the data-hub tutorial: https://marklogic.github.io/marklogic-data-hub/ leads to a GitHub 404 page.

This link is present in both [the README](https://github.com/marklogic-community/marklogic-data-hub/blob/1.0-master/README.md) and the developer.marklogic.com page: https://developer.marklogic.com/code/data-hub-framework.

#### Tech details

```
$ curl -v -X GET https://marklogic.github.io/marklogic-data-hub/ 2>&1 | grep HTTP
> GET /marklogic-data-hub/ HTTP/1.1
< HTTP/1.1 404 Not Found
```

**Comment by paxtonhare** [comment]
@dmcassel can you update https://developer.marklogic.com/code/data-hub-framework?

It needs updating after our repo relo.

**Comment by dmcassel** [comment]
Fixed. I'll take a look at the other /code pages, too.
