### ISSUE TITLE
Error when creating a harmonize flow based on entity definition

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic-community/marklogic-data-hub#454]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:
This flow has a bug!

What behavior are you expecting?

#### Tech details

Which Operating System are you using?
macOS Sierra 10.12.5

Which version of MarkLogic are you using?
9.0-1.1

Which version of the Data Hub Framework are you using?
2 Beta-1

Is this a QuickStart UI bug? If so, which browser are you using?

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

<img width="1922" alt="screen shot 2017-07-11 at 12 53 38" src="https://user-images.githubusercontent.com/15609655/28065413-b9361988-6638-11e7-8057-88f75896ee23.png">
<img width="1274" alt="screen shot 2017-07-11 at 12 53 51" src="https://user-images.githubusercontent.com/15609655/28065418-beacda46-6638-11e7-8ecf-e8cb755a6766.png">

**Comment by paxtonhare** [comment]
@sashamitrovich which version of MarkLogic are you using?

**Comment by paxtonhare** [comment]
We found the issue. It's a lowercase l in Marklogic vs needing to be MarkLogic. weird. We think regional settings make the case matter.
