### ISSUE TITLE
Quickstart Application not working on Internet Explorer

### ISSUE THREAD

**Issue by ayanjitnandy** [marklogic-community/marklogic-data-hub#456]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

quick-start-1.1.3.war file was moved into RHEL box and below command was executed:
java -jar -Dserver.port=8005 quick-start-1.1.3.war

In the command prompt the success message appeared as QuickStart UI Ready and Listening on port 8005;

However, while browsing through Internet Explorer, the page got stuck showing the message as "Quick Start Loading". 

This is the same server where ML is installed and running successfully at that moment.
What behavior are you expecting? 

#### Tech details

Which Operating System are you using? RHEL

Which version of MarkLogic are you using? Vesion 9

Which version of the Data Hub Framework are you using? quick-start-1.1.3.war

Also, the same file in windows env throwing the below error message:
18:49:14.957 [main] WARN  java.util.prefs - Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) return
ed error code 5.

Is this a QuickStart UI bug? If so, which browser are you using? Internet Explorer

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by ayanjitnandy** [comment]
Attaching the debugger file for quickstart
[myoutput.txt](https://github.com/marklogic-community/marklogic-data-hub/files/1156325/myoutput.txt)

**Comment by paxtonhare** [comment]
@ayanjitnandy which version of Internet Explorer were you using?

And can you check to see if it works in Chrome of FireFox?

**Comment by ayanjitnandy** [comment]
IE version is 11. But, it is working in google chrome
