### ISSUE TITLE
Sometimes a trace for a failed Harmonize job is not available/not existing

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic-community/marklogic-data-hub#461]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:
After running a Harmonize flow, the job trace is not available and the job failed. Difficult to understand why the flow failed.

What behavior are you expecting?

#### Tech details

Which Operating System are you using?
DHF and ML deployed on Windows 2012 Server, accessing the Quick Start app from a Windows laptop.

Which version of MarkLogic are you using?
9.0-1.1

Which version of the Data Hub Framework are you using?
v2 Beta 1

Is this a QuickStart UI bug? If so, which browser are you using?

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by paxtonhare** [comment]
@sashamitrovich can you double check that tracing is still enabled. There was a bug with redeploying manually that would wipe out the trace setting.

**Comment by paxtonhare** [comment]
@sashamitrovich also, if the tracing is still enabled, see if there was a trace logged for the collector. or if there was no trace whatsoever.

**Comment by sashamitrovich** [comment]
@paxtonhare, this was on-site with customer, can't check anymore, unfortunately.

**Comment by sashamitrovich** [comment]
I can confirm that the tracing setting was being wiped out after clicking on redeploy (manual redeploy). If this is fixed now (under another ticket), I suggest closing this as fixed.

**Comment by paxtonhare** [comment]
@sashamitrovich yep. wiping out was fixed. I'll close this one.
