### ISSUE TITLE
Saving the changes in a flow code never finishes *sometimes*

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic-community/marklogic-data-hub#462]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:
After clicking on the Save button, the cog wheel keeps spinning and spinning and never finishes saving.

What behavior are you expecting?

#### Tech details

Which Operating System are you using?
DHF and ML deployed on Windows 2012 Server, accessing the Quick Start app from a Windows laptop.

Which version of MarkLogic are you using?
9.0-1.1

Which version of the Data Hub Framework are you using?
v2 Beta 1

Is this a QuickStart UI bug? If so, which browser are you using?

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by paxtonhare** [comment]
@sashamitrovich can you open your javascript console and paste any errors you see into a comment here?
