### ISSUE TITLE
Method for invoking harmonization using XQuery only, i.e. for triggers

### ISSUE THREAD

**Issue by mikrovvelle** [marklogic-community/marklogic-data-hub#464]
#### The issue

There doesn't appear to be a way to invoke a harmonization using only XQuery. Harmonization methods expect only to be called from Java. This makes it difficult to find the right entry point for a trigger which would be written in XQuery or SJS.

#### Tech details

- on branch 2.0-develop, also seen on alpha release
- ML: 9.0-1.1
- OS: CentOS (but not OS-related)
- (not a UI bug)

#### The devil is in the details...

In the REST transform [`ml-modules/transforms/run-flow.xqy`](https://github.com/marklogic-community/marklogic-data-hub/blob/1.0-master/marklogic-data-hub/src/main/resources/ml-modules/transforms/run-flow.xqy#L26) you could theoretically invoke a harmonize flow, but the code forces the `$flow-type` variable to "input".

This might be the place to at least allow a flow invocation through REST without Java. It would then be easier to reach this via XQuery.

**Comment by paxtonhare** [comment]
@mikrovvelle I forgot to mention to you that you can invoke a Harmonize flow via rest with:

```
POST /v1/resources/flow?rs:entity-name=EntityName&rs:flow-name=FlowName&rs:flow-type=harmonize&job-id=abcd1234
```

This would require 2 http calls for you. One to insert the document then another to run the flow. Is that acceptable?

**Comment by paxtonhare** [comment]
I updated the wiki: https://github.com/marklogic-community/marklogic-data-hub/wiki/Advanced-Hub-Usage#3-rest-only-you-can-also-invoke-a-harmonize-flow-via-the-flow-rest-extension-the-caveat-here-is-that-you-will-not-be-able-to-run-the-collector-you-can-only-run-the-other-plugins-the-reason-for-this-is-that-java-invokes-the-collector-it-then-parallelizes-the-results-and-calls-flow-rest-extension-with-batches-of-ids

**Comment by mikrovvelle** [comment]
Thank @paxtonhare, I'm testing it now to see if I can make this work.

**Comment by paxtonhare** [comment]
I'm closing this because it was more of a lack of documentation.
