### ISSUE TITLE
Initializing DHF Project against existing DB is dropping indexes

### ISSUE THREAD

**Issue by bhandaru** [marklogic-community/marklogic-data-hub#468]
Initializing DHF against an existing final database dropping the indexes. In my observation it is dropping the element range indexes.

Steps to reproduce the issue.

1) Create a DB and add a few element range indexes to it.
2) Now initialize and deploy DHF project against that DB as final DB.

You should now see that the element range index created earlier is missing.

**Comment by paxtonhare** [comment]
@bhandaru this is expected behavior. You would need to add the existing indexes into the DHF user-config/databaes/${dbname}.json file so that DHF will know about them.
