### ISSUE TITLE
Example: Single-step ingest

### ISSUE THREAD

**Issue by paxtonhare** [marklogic-community/marklogic-data-hub#476]
Single-step ingest (where a trigger fires harmonization when the raw data is inserted). This needs to be mixed with other flows that work normally.

**Comment by damonfeldman** [comment]
Can we do this without a trigger? I always like to retain code-based control if possible, and think of triggers as mostly useful where you have a lot of legacy code, so can't be sure who's doing an update. Since we control the update path, perhaps we can add logic to the ingest flow to run the harmonize flow immediately.

Separately, this may entail writing less or no raw data. E.g. we might store a lightweight document in raw and have *more* data in harmonize, which would only be possible because the raw data in memory would need to be passed directly to the harmonize flow rather than being read from the raw db.

**Comment by dmcassel** [comment]
@damonfeldman I think you're suggesting skipping the input flow write and passing the content directly on to the harmonize flow. Intriguing. What about the case where the harmonization flow sometimes fails? In that case, you don't have the original raw record in the staging database, so it would need to be loaded from its original source again. It might be difficult to single out just the reloading the failed records, meaning the whole process needs to be repeated. Does that seem acceptable? Or is it better to have the input flow run normally, then kick off harmonization?

**Comment by mhuang-ml** [comment]
@damonfeldman and @dmcassel, is there a consensus regarding the approach to this ticket?  I can see both sides to implementing this.  Just trying to summarize both viewpoints:
1.  If we utilize triggers, then the document will be persisted into the STAGING database and then we'd have to query that document to write the harmonized document into the FINAL database.  This approach will allow the harmonization process to essentially pick up from where it left off if there is an error with harmonization though and data will **NOT** need to be re-ingested.
2.  If we have the ingest flow immediately call the harmonization flow, then we run the risk of an error during the harmonization process, the raw data would need to be re-ingested and there may need to be logic that is implemented to figure out which documents were successfully harmonized and which documents need to be re-ingested and harmonized.

**Comment by mhuang-ml** [comment]
@paxtonhare and @dmcassel, for the examples of triggers firing, then would you want the trigger implementation module to call the flow.xqy:post() service method or should it call the flow-lib.xqy:run-flow() module method?

I've got an example of the triggers working for the online-store demo that is using the flow.xqy:post() service method at the moment, but I can easily change the trigger to call the flow-lib.xqy:run-flow() method directly.  Just wanted to double check with both of you on which method I should call.

**Comment by damonfeldman** [comment]
@mhuang-ml  - There is some useful code in flow.xqy:post() that I think should be re-used, but it feels funny to call post() as a function from the ingest flow. In particular, it returns a "404" message and such, and the returned $resp document should be integrated into the ingest flow response, I think. It's tricky.

Also, the "batch" logic for ingest is in the mlcp/REST code, but harmonize flows deal with their own batch of documents (list of IDs in the #params map). So there's a mismatch there. 

How about a new REST endpoint that takes a bunch of documents for ingest, and processes them all but allows a writer to be specified (neither /v1/documents REST, nor mlcp). This should also allow MUCH better performance by looking up the flows once and running the ingest in a loop, and we could have options to store it all directly to the Final DB if desired.

**Comment by mhuang-ml** [comment]
@damonfeldman - I touched base with @aebadirad  regarding this example and what we came up with is the following:
- Put together a custom REST endpoint that will accept a document and insert it into the STAGING database
- The document that would be inserted into the STAGING database will be passed in an eval to the harmonization flow so we will have a one-to-one relationship between the document ingested from the endpoint to the harmonized document
- Essentially, we're going to bypass the collector plugin from the harmonization flow and eval the flow-lib.xqy:run-flow() function

**Comment by aebadirad** [comment]
This was merged in so closing issue.
