### ISSUE TITLE
Input flow (mlcp) options aren't saved

### ISSUE THREAD

**Issue by sjcrook** [marklogic-community/marklogic-data-hub#481]
Having clicked the save options button, when I return to the screen later, the options aren't what they were immediately after I clicked saved.  I'm running quick-start-2.0.0-rc.1 on a Mac against ML9.0-1.1

**Comment by paxtonhare** [comment]
@sjcrook is there a particular option or options that weren't saving? I can't reproduce this.

Were there any errors in your terminal window? or in the browser javascript console?

**Comment by sjcrook** [comment]
It's the output_uri_replace.  I can see that it successfully writes the options to the file.  However, it doesn't pick it up again.  It could be to do with the regex: /Users/scrook/Downloads/patient-360-1/patient\-,''
