### ISSUE TITLE
ML behind Firewall + different ports

### ISSUE THREAD

**Issue by kosed** [marklogic-community/marklogic-data-hub#489]
### The issue

Say you have your ML install behind a firewall.
you staging App server port is 8010 (in your gradlde.properties, `mlStagingPort=8010`)
but is reachable outside through 30000

Then you try deploying your modules with `./gradlew mlDeploy`

- The DHF will complain because not able to reach the server on port 8010.
=> Normal since the port is not opened
- If you manually change the gradlde.properties => `mlStagingPort=30000`
=> DHF will find that the port has changed and update the config of the appServer to match what is in the config file. Cool, now you can get to the firewall but not to your Appserver since the firewall is sending data to the port 8010.

One possible solution could be to have different ports like mlStagingPort (real server port) and mlStagingPortOutside (for the accessing it)

#### Tech details

Which version of MarkLogic are you using?
9.0-2

Which version of the Data Hub Framework are you using?
2.0.0-rc.1

**Comment by paxtonhare** [comment]
@rjrudin have you dealt with any port remapping issues before with ml-gradle?

**Comment by paxtonhare** [comment]
@kosed have you tried ssh tunneling? This is such an obscure need. I'm curious, why did your IT group decide to do port rewriting?

**Comment by kosed** [comment]
I actually am ML consulting @paxtonhare.
My particular case showed up because I work with a number of dockerized ML nodes with the same app ports. I therefore forward those ports (to different ones) to my main computer which also holds the dev environment and the DHF.
I think it is an interesting feature to decorrelate the actual app port from the client visible one.
Of course it's a matter of priority and there are other options available to make it work with my docker setup including using different ports on the different containers (or SSH like you suggest).

**Comment by paxtonhare** [comment]
@kosed I could be mistaken, but I think this is a use case for docker networks. You can create your own mini network that the host/cluster runs on. Then you won't have these port conflict issues.

**Comment by kosed** [comment]
Hello @paxtonhare thanx for the hint.
My specific docker case is solved as I have redistributed the ports so that containers will use different ports that can be mapped "as-is" :-) to the ports on my computer.
