### ISSUE TITLE
Add Spring-Batch jobRepo configuration to data-hub-JOBS database & app-server?

### ISSUE THREAD

**Issue by mikrovvelle** [marklogic-community/marklogic-data-hub#493]
1. The issue

The first step in the [spring-batch example](https://github.com/marklogic-community/marklogic-data-hub/tree/2.0-develop/examples/spring-batch) is "Deploy the MarkLogic Job Repository". This links to the [mlJobRepo](https://github.com/marklogic-community/marklogic-spring-batch/wiki/MarkLogicJobRepository) script/project. Running this sets up an additional content database, modules database and HTTP server exclusively for the purpose of tracking the ML-Spring-Batch jobs.

I think it would make sense to use the existing DHF "Jobs" content database, DHF modules database, and the JOBS HTTP server. This would simplify the Spring-Batch example, and eliminate the need to go to another project, and download and run a bash/bat script.

At first glance, it doesn't look like there would be any overlap or collisions:

* ML Spring Batch stores its jobs in the directory "/projects.spring.io/spring-batch/" and "http://marklogic.com/spring-batch/job-instance" collection, while
* DHF uses the "/jobs/" directory and "job" collection.
* ML Spring batch element-range indexes are safely set aside in the "http://marklogic.com/spring-batch" XML namespace.
      1. Which version of the Data Hub Framework are you using?

2.0-develop branch

┆Status: Eng Reviewed

**Comment by miguelrgonzalez** [comment]
For now, I'm disabling batch config, but I would like to see these two merged as well.

marklogic.batch.config.enabled=false

**Comment by sastafford** [comment]
I submitted #622 for this.  Just need a review.

**Comment by aebadirad** [comment]
This was added in the pull that was accepted from #622

**Comment by dmcassel** [comment]
➤ Alexander Ebadirad commented:

We pulled this in from [~sstafford]
