### ISSUE TITLE
Next button not working when browsing to new hub project directory

### ISSUE THREAD

**Issue by damonfeldman** [marklogic-community/marklogic-data-hub#502]
#### The issue

When I open the data hub gui and try to select a new data hub directory but select the default (without interacting at all with the file chooser) the Next button does nothing.

If I click around a bit in the file chooser (web-based file chooser) then I can move on and the Next button works.

What behavior are you expecting?
To accept the default by clicking next.

#### Tech details

Which Operating System are you using?
OSX

Which version of MarkLogic are you using?
n/a - bug is before ML interaction

Which version of the Data Hub Framework are you using?
1.1.3

Is this a QuickStart UI bug? If so, which browser are you using?
Yes. Chrome.

**Comment by paxtonhare** [comment]
This appears to be fixed in a later build.
