### ISSUE TITLE
Error loading XSD schemas

### ISSUE THREAD

**Issue by luisjmart** [marklogic-community/marklogic-data-hub#509]
Short description of the problem:

The task mlLoadSchemas fails when the Staging App Server is set with:
    {
        "server-name": "%%mlStagingAppserverName%%",
        "collation":"http://marklogic.com/collation/codepoint"
    }

:mlLoadSchemasException in thread "ThreadPoolTaskExecutor-1" com.marklogic.client.FailedRequestException: Local message: failed to apply resource at documents: Internal Server Error. Server Message: XDMP-AS: (err:XPTY0004) $uri as xs:string -- Invalid coercion: () as xs:string . See the MarkLogic server error log for further detail.
        at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4311)
        at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3305)

        at com.marklogic.client.impl.JerseyServices.postBulkDocuments(JerseyServices.java:3395)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:613)
        at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)

        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:605)
        at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:589)
        at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
        at com.marklogic.client.batch.RestBatchWriter$1.run(RestBatchWriter.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

#### Tech details

Which version of MarkLogic are you using?

  ML8.0-6 and ML8.0-7 

Which version of the Data Hub Framework are you using?

  DHF-1.1.3

**Comment by paxtonhare** [comment]
Several people have had issues lately. There are 2 possible fixes that we've seen.

```bash
gradle --no-daemon mlLoadSchemas
```

If that doesn't fix it then try changing the default collation on your REST API to the root collation. Someone had success with that.

Let me know via this ticket if either worked.

**Comment by luisjmart** [comment]
`gradle --no-daemon mlLoadSchemas`

does not fix the problem

I reported that changing the default collation on the Staging appserver to Root fixes loading the XSDs. But why would schema loading required Root collation?  We are trying to avoid updating all the query code to not use the default appserver collation.

To add, a simple ml-gradle project does not have this problem regardless of what the appserver collation is set to.

**Comment by paxtonhare** [comment]
@luisjmart In order to truly fix this I will need to update DHF to use version 3.0.0 of ml-gradle.

But in the meantime, here is some gradle-fu to get you through:

```groovy
buildscript {
  repositories {
    maven {url 'http://developer.marklogic.com/maven2/'}
    jcenter()
  }
  dependencies {
    if (gradle.startParameter.taskNames*.toLowerCase().contains("schemasgo")) {
        classpath "com.marklogic:ml-gradle:3.0.0"
    }
    else {
        classpath "com.marklogic:ml-gradle:2.9.0"
        classpath "gradle.plugin.com.marklogic:ml-data-hub:1.1.3"
    }
  }
}

plugins {
    id 'java'
    id 'eclipse'
    id 'idea'

    // This plugin allows you to create different environments
    // for your gradle deploy. Each environment is represented
    // by a gradle-${env}.properties file
    // See https://github.com/stevesaliman/gradle-properties-plugin
    // specify the env on the command line with:
    // gradle -PenvironmentName=x ...
    id 'net.saliman.properties' version '1.4.6'

    // This gradle plugin extends the ml-gradle plugin with
    // commands that make the Data Hub Framework do its magic
    // id 'com.marklogic.ml-data-hub' version '1.1.3'
}

apply plugin: "com.marklogic.ml-gradle"

if (!gradle.startParameter.taskNames*.toLowerCase().contains("schemasgo")) {
    apply plugin: "com.marklogic.ml-data-hub"
}

repositories {
    jcenter()
    maven {url 'http://developer.marklogic.com/maven2/'}
}

dependencies {
    // this allows you to write custom java code that depends
    // on the Data Hub Framework library
    // compile 'com.marklogic:marklogic-data-hub:1.1.3'
    compile 'com.marklogic:ml-app-deployer:3.0.0'
    compile 'com.marklogic:marklogic-xcc:9.0.2'
}

task schemasGo(type: com.marklogic.gradle.task.schemas.LoadSchemasTask)

ext {
    mlAppDeployer.getCommands().remove(mlAppDeployer.getCommand("LoadSchemasCommand"))
    mlAppConfig.schemasDatabaseName = "data-hub-SCHEMAS"
}
```

To load the schemas you will have to deliberately type:

```bash
gradle schemasGo
```

**Comment by paxtonhare** [comment]
#505 will fix this.
