### ISSUE TITLE
Input Flow for Binary files  (like jpegs)

### ISSUE THREAD

**Issue by rogomezh** [marklogic-community/marklogic-data-hub#520]
#### The issue

When creating  a new input flow, in order to upload jpeg files at the moment of selecting  the input file type, I cannot see the binary option,  what type should I be selecting, or is the binary option missing?

![image](https://user-images.githubusercontent.com/17832446/30992904-c14344e4-a471-11e7-8563-f0e6e89e6fcc.png)

What behavior are you expecting?

Find Binary as an Input File Type

#### Tech details

Which Operating System are you using?
Windows 10
Which version of MarkLogic are you using?
ML 9
Which version of the Data Hub Framework are you using?
2.0
Is this a QuickStart UI bug? If so, which browser are you using?
chrome

**Comment by gregnist** [comment]
I recently created an input flow to load PNG files. I was successful with the following:

First, set the **Input File Type = Documents**:
![image](https://user-images.githubusercontent.com/1749707/30993205-cbd443a4-a47b-11e7-9198-8febc71381f2.png)

Then set the **Document Type = Binary**:
![image](https://user-images.githubusercontent.com/1749707/30993236-ed15cd6c-a47b-11e7-8e14-7d5c0f3d8e06.png)

Hope this helps!

**Comment by rogomezh** [comment]
thanks,   this will do it, I was expecting the option on the wrong place
