### ISSUE TITLE
namespace of headers and triples

### ISSUE THREAD

**Issue by tzejohn** [marklogic-community/marklogic-data-hub#524]
This is related to #436. I understand the desired naming change to be in line with the naming in entity-services. i.e. with the envelope and instance and attachments, as the document stored is an "entity". But are headers and triples actual elements in the `http://marklogic.com/entity-services`  namespace? They are not mentioned in the spec, and so seem to be data hub specific. So, should they not be in a data hub specific namespace, or are we ok with populating stuff in the entity-services namespace?

**Comment by paxtonhare** [comment]
@tzejohn You are correct that headers and triples are not part of the ES envelope. Luckily ES doesn't care if you enhance the envelope and there is no harm in doing so. As for the namespace, I chose to keep it all ES just for simplicity.

**Comment by popzip** [comment]
Hopefully your question is resolved
