### ISSUE TITLE
incorrect scaffolding

### ISSUE THREAD

**Issue by tzejohn** [marklogic-community/marklogic-data-hub#525]
In [/src/main/resources/scaffolding/harmonize/xqy/content.xqy](https://github.com/marklogic-community/marklogic-data-hub/blob/master/marklogic-data-hub/src/main/resources/scaffolding/harmonize/xqy/content.xqy)
The generated scaffolding code is incorrect with the namespace in the second condition. It is missing the `es` prefix.

```xquery
if ($doc/es:envelope) then
  $doc/es:envelope/es:instance/node()
else if ($doc/envelope/instance) then
  $doc/envelope/instance
else
  $doc
```

**Comment by paxtonhare** [comment]
@tzejohn Actually that 2nd case covers json documents. It's not a bug.
