### ISSUE TITLE
Add detailed documentation on traces

### ISSUE THREAD

**Issue by paxtonhare** [marklogic-community/marklogic-data-hub#527]

**Comment by tcfenstermaker** [comment]
Can you provide a little more detail?

**Comment by paxtonhare** [comment]
This is more about updating the wiki to better document traces.

1. what is a trace?
1. when is it used?
1. what is the format?
1. How do I view traces?

**Comment by paxtonhare** [comment]
traces are controlled by a flag in the Modules db. there is a gradle task to enable/disable them.

Traces will fire, even if disabled, when an uncaught exception occurs.

Traces live in the traces db. There is a viewer on port 8012 or whichever port your trace appserver is on. This is installed into MarkLogic and you do not need the quickstart app. You can also view them with quickstart.

**Comment by tcfenstermaker** [comment]
I'll create a wiki page linked off the main for this.

**Comment by tcfenstermaker** [comment]
Have a basic page up here: https://github.com/marklogic-community/marklogic-data-hub/wiki/Traces

Still needs screenshots, but I'm waiting to hear whether this page is getting migrated first.  Afterwards needs to be linked to another page (for now only accessible from page index).

**Comment by tcfenstermaker** [comment]
Uploaded images here:

https://github.com/marklogic-community/marklogic-data-hub/tree/design/images/screenshots/flow-tracing

And added them to the page; then added a link to the page here:

https://github.com/marklogic-community/marklogic-data-hub/wiki/Hub-Basics

Done with this ticket for the time being; as I use tracing and learn more, will add information to the page that looks like it should be called out.
