### ISSUE TITLE
Browse Data: not obvious that I needed to click Search

### ISSUE THREAD

**Issue by dmcassel** [marklogic-community/marklogic-data-hub#530]
On the Browse Data page, I wanted to switch from the staging database to final. I changed the drop down selector. There's no button next to it, so I thought it would just make the change. It doesn't. 

Consider having the search automatically run when you change the database. 

#### Tech details

Which Operating System are you using? Docker on Mac

Which version of MarkLogic are you using? 9.0-2

Which version of the Data Hub Framework are you using? 2.0.0

**Comment by paxtonhare** [comment]
duplicate of #535
