### ISSUE TITLE
mlWatch broken for deploying REST extensions 

### ISSUE THREAD

**Issue by tternquist** [marklogic-community/marklogic-data-hub#538]
#### The issue

Short description of the problem:
gradle mlWatch fails when change is made to REST extension

What behavior are you expecting?
Expect it to not fail :) 
#### Tech details
Which Operating System are you using?
MacOS Sierra
Which version of MarkLogic are you using? 9.0-3

Which version of the Data Hub Framework are you using? 2.0.0

Is this a QuickStart UI bug? If so, which browser are you using? No

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

![image](https://user-images.githubusercontent.com/867568/31293621-bc200ae4-aaa5-11e7-876e-63b832b49bfe.png)

**Comment by paxtonhare** [comment]
@tternquist Thanks for catching this.
