### ISSUE TITLE
hubPreinstallCheck, AdminConfig ignores SSL setting

### ISSUE THREAD

**Issue by mikrovvelle** [marklogic-community/marklogic-data-hub#539]
#### The issue

With a Datahub project using the following settings:

```properties
mlAdminScheme=https
mlAdminSimpleSsl=true
```

The settings get ignored during the `hubPreInstallCheck` task. This task calls the [`newAdminManager()` function in the `HubConfig` class](https://github.com/marklogic-community/marklogic-data-hub/blob/e172e5d74b81743942eecfabb8fa4e93ba559b36/marklogic-data-hub/src/main/java/com/marklogic/hub/HubConfig.java#L291). The function only sets host, port, username and password.

The `configureSimpleSsl` never gets set to true, so when the REST call is finally made, it attempts over HTTP. This leads deployment to fail on a server where the admin app-server uses HTTPS.

#### Tech details

> Which Operating System are you using?

any

> Which version of MarkLogic are you using?

9.0-3

> Which version of the Data Hub Framework are you using?

2.0.0

> Is this a QuickStart UI bug? If so, which browser are you using?

Not specific to QuickStart UI

**Comment by paxtonhare** [comment]
Until this is fixed you can turn it off via build.gradle:

```groovy
project.tasks.mlDeploy.dependsOn.remove("hubPreInstallCheck")
```
