### ISSUE TITLE
2.0.0 unavailable in maven ?

### ISSUE THREAD

**Issue by ltnd** [marklogic-community/marklogic-data-hub#540]
The DHF 2.0 has been released but when we try to add the dependance in maven, the package is not found :
```
<dependency>
  <groupId>com.marklogic</groupId>
  <artifactId>marklogic-data-hub</artifactId>
  <version>2.0.0</version>
  <type>pom</type>
</dependency>
```

┆Status: To Do

**Comment by paxtonhare** [comment]
@ltnd It should be there. Try again.

**Comment by ltnd** [comment]
It's not in maven central (https://repo.maven.apache.org/maven2/com/marklogic/) nor in atlassian (https://maven.atlassian.com/maven-external/com/marklogic/marklogic-data-hub/ => no 2.0.0 version).

On which maven repo is it available ?

**Comment by paxtonhare** [comment]
It's in bintray. https://bintray.com/paxtonhare/maven/marklogic-data-hub

I'll see about getting it in maven central.

**Comment by ltnd** [comment]
Thanks paxton ! 
(If not possible to publish it in maven central, perhaps in marklogic repo at http://developer.marklogic.com/maven2/com/marklogic/ ? )

**Comment by grechaw** [comment]
Hi @ltnd bintray it seems has really supplanted maven central.  You'll find that the dependencies for the Java Client API 3.0.8 and 4.0.2 are also not in maven central, through choices of the authors.

It should be trivial to configure your project to use bintray.  It's the same as a maven repo from client perspective -- have you tried to just configure your projects that way?

**Comment by paxtonhare** [comment]
I'm in agreement with Charles. The repo on developer.marklogic.com is NOT
ideal. Bintray is way more standard.

**Comment by popzip** [comment]
@aebadirad confirming bintray is the plan, should we close?

**Comment by popzip** [comment]
The plan is to also push to maven central for 3.0 release.
