### ISSUE TITLE
Update hubCreateEntity task to use ES too

### ISSUE THREAD

**Issue by paxtonhare** [marklogic-community/marklogic-data-hub#547]
Right now hubCreateEntity just creates a directory. It should scaffold a barebones ES model def is requested.

**Comment by popzip** [comment]
modify the existing hubCreateEntity gradle task to use the ES model to make a flow. This is available on the UI already.

**Comment by paxtonhare** [comment]
TODO: put a gradle-fu workaround for this here for those folks who need it sooner than the release.next.
