### ISSUE TITLE
Add support for mlcp -input_file_pattern

### ISSUE THREAD

**Issue by bobstarbird** [marklogic-community/marklogic-data-hub#550]
Trying to limit the files processed by mlcp during input flow.
Directories contain many unrelated files so would like to regex pattern match filenames.

**Comment by damonfeldman** [comment]
Can mlcp do that somehow? Quickstart embeds and spits out a config for mlcp, and running headless (without the quickstart GUI) you'd just run an mlcp batch job. If not, ml-spring-batch may work.

**Comment by paxtonhare** [comment]
![image](https://user-images.githubusercontent.com/630382/31999414-1fc36b80-b961-11e7-84c7-3e2e15755ea4.png)

@bobstarbird looks like it's already there.
