### ISSUE TITLE
Getting MISSING_FLOW error when invoking from DMSDK

### ISSUE THREAD

**Issue by janmichaelyu** [marklogic-community/marklogic-data-hub#552]
#### The issue

In the title and I don't know if this is a datahub issue or a DMSDK issue.
This is found to be working in a customer cluster but locally give the attached errors. 

I confirm the properties are not null, please see the access log which shows the call has the parameters. 

Also, I confirm that this is working from the quickstart UI, it's just from this DMSDK scenario where I get this problem.

#### Tech details

Which Operating System are you using?
Linux
Which version of MarkLogic are you using?
9.0.3
Which version of the Data Hub Framework are you using?
2.0.0
Is this a QuickStart UI bug? If so, which browser are you using?
Likely not.

#### ErrorLog from ML
13:38:13.046 [pool-1-thread-10] WARN  c.m.c.d.impl.WriteBatcherImpl - Error writing batch: com.marklogic.client.FailedRequestException: Local message: failed to apply resource at documents: Internal Server Error. Server Message: The specified flow : is missing. (MISSING_FLOW): . See the MarkLogic server error log for further detail.

#### AccessLog from ML
172.28.128.1 - admin [26/Oct/2017:05:37:42 +0000] "POST /v1/documents?trans:job-id=2bcab367-2764-4d93-be95-3eb5603cf244&transform=run-flow&trans:options={%22targetEntity%22:%22TruvenEnrollment%22}&trans:entity=GenericEnvelope&trans:flow=basic&database=abbvie-es-data-hub-STAGING HTTP/1.1" 500 221 - "okhttp/3.8.1"

Java code
`
		ServerTransform runFlow = null;

			runFlow = new ServerTransform("run-flow");
			String dataHubEntity = entityName;
			if (properties.containsKey("dataHubEntity")) {
				dataHubEntity = properties.getProperty("dataHubEntity");
			}
			runFlow.addParameter("entity", dataHubEntity);
			runFlow.addParameter("flow", properties.getProperty("dataHubFlow"));
			runFlow.addParameter("job-id", UUID.randomUUID().toString());
			try {
				runFlow.addParameter("options", new JSONObject().put("targetEntity", entityName).toString());
			} catch (JSONException e) {
				e.printStackTrace();
			}
		`

**Comment by damonfeldman** [comment]
I don't see the flow type in there (input). Is that needed perhaps?

Note there is a SpringBatch writer to invoke the data hub, which may or may not be appropriate given all the batching in this use case.

**Comment by paxtonhare** [comment]
@damonfeldman flowtype is no longer needed. you can only run harmonize flows via that avenue so I took out the superfluous param.

**Comment by paxtonhare** [comment]
@janmichaelyu note that you are using the old param names. See here for the 2.0.0 param names: https://github.com/marklogic-community/marklogic-data-hub/wiki/Advanced-Hub-Usage#3-via-the-marklogic-java-client-api

**Comment by paxtonhare** [comment]
@janmichaelyu did you try the updated param names yet? May I close this ticket?

**Comment by janmichaelyu** [comment]
Apologies, somehow lost my notifications. Will be reviewing and trying to get this working.

**Comment by janmichaelyu** [comment]
Awesome, now works when I changed 'entity' to 'entity-name' and 'flow' to 'flow-name'.
Strange why this is not the case on the customer environment. Might be an old deployment and a new deployment was never run.
