### ISSUE TITLE
Update Hub ES code to get inline with newer ES features

### ISSUE THREAD

**Issue by paxtonhare** [marklogic-community/marklogic-data-hub#553]
Looks like ES added support for range indexes and namespaces. Need to update the hub code.

┆Status: To Do

**Comment by popzip** [comment]
Also evaluate if other short/long term updates (to DHF or ES) to get more in line. (May not do all the changes but identify).

**Comment by popzip** [comment]
Will also address JSON changes https://github.com/marklogic-community/marklogic-data-hub/issues/577

**Comment by dmcassel** [comment]
➤ Kasey Alderete commented:

finished earlier, got duplicated by the unito sync

https://project.marklogic.com/jira/browse/DHFPROD-4
