### ISSUE TITLE
Blank harmonization page

### ISSUE THREAD

**Issue by kghmanuel** [marklogic-community/marklogic-data-hub#558]
Harmonization page is blank if the folder created is not the same as the entity name, e.g. folder created is Bug_Report, while the entity is bug_report. This can happen if the entity title is modified.

#### Tech details

Which Operating System are you using? Windows 7

Which version of MarkLogic are you using? ML 9.0-2

Which version of the Data Hub Framework are you using? 2.0.0

Is this a QuickStart UI bug? If so, which browser are you using? Yes, chrome.

#### The devil is in the details...

There is no difference in output in the logs nor in the browser console.

**Comment by dmcassel** [comment]
Steps to reproduce:

- Run QuickStart
- Go to Entities tab
- create an entity
- rename the entity by editing on the Entities view
- go to the Flows tab
- create an Input or Harmonize flow for that entity
- click on the flow -- no screens for the flow will appear
