### ISSUE TITLE
Harmonize Writer could benefit from more context like $type

### ISSUE THREAD

**Issue by bobstarbird** [marklogic-community/marklogic-data-hub#564]
As a developer I would like to dynamically build the entity using $type. Then envelope uses $type but the writer does not receive this context info in options. May be passing content in options or just $type and $version.

**Comment by paxtonhare** [comment]
@bobstarbird when you say $type... do you mean `map:get($options, "dataFormat")`?

You want to know if it's xml or json?

**Comment by bobstarbird** [comment]
I wanted the entity type which I updated during content processing. I realize now this was because JSON was not getting the envelope info block. Closing issue.
