### ISSUE TITLE
REST search options deployed to wrong location in modules db

### ISSUE THREAD

**Issue by grechaw** [marklogic-community/marklogic-data-hub#567]
### Welcome Hub enthusiast!

Thank you

#### The issue

I put a search options in a location inspired by code and samples  plugins/ENTITY/harmonize/REST/options/Project.xml

It was deployed to the modules bd, but to with a path that REST API recognized:
`/Default/data-hub-FINAL/rest-api/options/Project.xml`

What behavior are you expecting?

Search options path start with `marklogic.restapi.options` or something like that.

#### Tech details

Which Operating System are you using?

Windows

Which version of MarkLogic are you using?

a nightly build 

Which version of the Data Hub Framework are you using?

2.0.0

Is this a QuickStart UI bug? If so, which browser are you using?

no

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

```
tern [file:///C:/space/MarkLogic/git/data-workbench/plugins/entities/Project/harmonize/REST//transforms/*.xsl*] to resources []
08:16:46.267 [DEBUG] [org.springframework.core.io.support.PathMatchingResourcePatternResolver] Looking for matching resources in directory tree [C:\space\MarkLogic\git\data-workbench\plugins\entities\Project\harmonize\REST\transforms]
08:16:46.267 [DEBUG] [org.springframework.core.io.support.PathMatchingResourcePatternResolver] Skipping [C:\space\MarkLogic\git\data-workbench\plugins\entities\Project\harmonize\REST\transforms] because it does not exist
08:16:46.267 [DEBUG] [org.springframework.core.io.support.PathMatchingResourcePatternResolver] Resolved location pattern [file:///C:/space/MarkLogic/git/data-workbench/plugins/entities/Project/harmonize/REST//transforms/*.sjs] to resources []
08:16:46.267 [INFO] [com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader] Loading Project query options from file Project.xml
08:16:46.272 [DEBUG] [com.marklogic.client.impl.OkHttpServices] Putting /config/query/Project
08:16:46.277 [DEBUG] [com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader] shutdownTaskExecutorAfterLoadingModules is set to false, so not shutting down taskExecutor
08:16:46.278 [DEBUG] [com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader] Finished loading modules from base directory: C:\space\MarkLogic\git\data-workbench\plugins\entities\Project\harmonize\REST
08:16:46.286 [DEBUG] [com.marklogic.client.impl.OkHttpServices] Posting documents
08:16:46.286 [DEBUG] [com.marklogic.client.impl.OkHttpServices] Sending multipart for /v1/documents
08:16:47.990 [INFO] [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor] Shutting down ExecutorService
08:16:48.096 [INFO] [com.marklogic.appdeployer.impl.SimpleAppDeployer] Finished executing command [com.marklogic.hub.deploy.commands.LoadUserModulesCommand]

08:16:
```

not very useful output.

**Comment by paxtonhare** [comment]
@grechaw are you sure the path that gets inserted is wrong? It's being added by the REST api and should be legit.

**Comment by grechaw** [comment]
I'm looking back over.  my options definitely did not work for some reason, but maybe not because the path is wrong.  I just tried on another ml-gradle option and the options all work properly, while the path is not what I would have expected.  Stand by, this is waiting on more info from me.

**Comment by grechaw** [comment]
I blew away my data dir started over, and this issue is no longer an issue.  sorry for the noise.  I'm curious whether ELS interacts with REST in some way -- ever since working on ELS example for entity-services, subtle things about security changed
