### ISSUE TITLE
info block for JSON

### ISSUE THREAD

**Issue by bobstarbird** [marklogic-community/marklogic-data-hub#577]
JSON envelope documents are missing info blocks.

I think flow-lib.xqy should be:

    declare function flow:make-envelope($content, $headers, $triples, $data-format)
      as document-node()
    {
      let $content := flow:clean-data($content, "content", $data-format)
      let $headers := flow:clean-data($headers, "headers", $data-format)
      let $triples := flow:clean-data($triples, "triples", $data-format)
      return
        if ($data-format = $consts:JSON) then
          let $envelope :=
            let $o := json:object()
            let $_ := (
              map:put($o, "headers", $headers),
              map:put($o, "triples", $triples),
              map:put($o, "instance",
                if ($content instance of map:map and map:keys($content) = "$type") then
                  let $json := flow:instance-to-canonical-json($content)
                  let $info := json:object()
                  let $_ := (
                    map:put($info, "$title", "$type"),
                    map:put($info, "$version",  "$version"))
                    
                  let $i := json:object()
                  let $_ := (
                    map:put($i, "info", $info),
                    for $k in map:keys($json)
                    return
                      map:put($i, $k, map:get($json, $k)))
                  return $i
                else
                  $content
              ),
              map:put($o, "attachments",
                if ($content instance of map:map and map:keys($content) = "$attachments") then
                  map:get($content, "$attachments")
                else
                  ()
              )
            )
            return
              $o

┆Status: To Do

**Comment by bobstarbird** [comment]
Typo in my proposed code. Info block should be populated with content values:

              let $info := json:object()
              let $_ := (
                map:put($info, "$title", map:get($content, "$type")),
                map:put($info, "$version",  map:get($content, "$version")))

**Comment by popzip** [comment]
@paxtonhare done?

**Comment by dmcassel** [comment]
➤ Bob Starbird commented:

From what I saw in the new code it looks done and works for me
