### ISSUE TITLE
The mlUndeploy task does not completely remove a data hub

### ISSUE THREAD

**Issue by dmcassel** [marklogic-community/marklogic-data-hub#580]
#### The issue

Given an installed data hub, running `./gradlew mlUndeploy` should remove it. However, it errors out and leaves several components. 

#### Workaround

Manually delete the jobs app server, jobs database, and jobs forest, then re-run. 

#### Tech details

Which Operating System are you using? Mac + Linux in Docker

Which version of MarkLogic are you using? 9.0-2

Which version of the Data Hub Framework are you using? 2.0.0

Is this a QuickStart UI bug? If so, which browser are you using? No

#### The devil is in the details...

```
 $ ./gradlew mlUndeploy
:marklogic-data-hub:mlUndeployApp
Logging HTTP response body to assist with debugging: <error xmlns="http://marklogic.com/xdmp/error">
  <status-code>500</status-code>
  <status>Internal Server Error</status>
  <message-code>ADMIN-DATABASEINUSE</message-code>
  <message>ADMIN-DATABASEINUSE: (err:FOER0000) The following webdav-servers still refer to this database: data-hub-JOBS.</message>
</error>

:marklogic-data-hub:mlUndeployApp FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':marklogic-data-hub:mlUndeployApp'.
> 500 Internal Server Error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by popzip** [comment]
@dmcassel - done?

**Comment by dmcassel** [comment]
yes
