### ISSUE TITLE
Object type changed after upgrade to Hub 2.0 so fields are missing or undefined

### ISSUE THREAD

**Issue by damonfeldman** [marklogic-community/marklogic-data-hub#583]
#### The issue

Short description of the problem:

Data Hub 1.1.3 passed in the 'content' parameter to the headers plugin as a regular JSON Object, but the newly-generated main.sjs code added when upgrading to Hub 2.0 passes content in as a MarkLogic Document. Therefore you have to call toObject() on it in order to access fields.

What behavior are you expecting?
The header plugin to run without modification after upgrade.

#### Tech details

Which version of the Data Hub Framework are you using?
Upgraded from 1.1.3 to 2.0

Is this a QuickStart UI bug? If so, which browser are you using?
no

**Comment by damonfeldman** [comment]
Depending on the nature of the fix, this may be somewhat urgent (or at least time critical), because if the fix will be to change the content parameter back to a regular JSON object, then everyone who's writing code against 2.x today (and uses content in the headers/triples plugins) will see errors when they get the fix.

OTOH, if the document object is the way forward, or some tricky code to introspect into the object is used, that won't be an issue - but we can then update the 2.x upgrade docs immediately.

**Comment by dmcassel** [comment]
@popzip We updated the docs to reflect this. Can we close this issue?
