### ISSUE TITLE
Quickstart runs in 2.0 mode only for version 9, not > 9.x

### ISSUE THREAD

**Issue by grechaw** [marklogic-community/marklogic-data-hub#591]
If you start up the quickstart with a version 10 MarkLogic server, it does not use entity services as it should.

@paxtonhare  has found the location of the bug:

*ngIf="getMarkLogicVersion().startsWith('9')"

I expect the 9.0 interface to entities.

#### Tech details

Windows

Which version of MarkLogic are you using?

10 nightly

Which version of the Data Hub Framework are you using?

2.0.0 

Is this a QuickStart UI bug? If so, which browser are you using?

yes, doesn't matter though.

#### The devil is in the details...

You're a genius you don't need details

**Comment by aebadirad** [comment]
This should now be fixed with 2.0.3 release, reopen please if it's not.
