### ISSUE TITLE
Initial set up working but not individual commands

### ISSUE THREAD

**Issue by Vikas1234** [marklogic-community/marklogic-data-hub#611]
Hi All,

I am new to data-hub .I have followed these steps but  unable to run individual commands

1) created one folder
2) put initial files in folder (build.gradle , gradle.properties,gradlew,gradlew.bat) .These files taken from markogic-data-hub directory
3) run a command mlNewProject and fill details about the project
4) mlDeploy build successful and relected in marklogic 
5) Want to deploy index again after adding some new index in ml-config folder.
6) Running gradle mlReindexdatabase -PdbName=testml-content
    build successful

  but indexing not happen  in database
  Getting message like sending request to database but it is not reflecting.in database indexing

**Comment by dmcassel** [comment]
Vikas, to get started with a project, please follow the steps show at https://marklogic-community.github.io/marklogic-data-hub/project/gradle/. In particular, you'll use the hubInit task rather than mlNewProject.
