### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by Vikas1234** [marklogic-community/marklogic-data-hub#614]
Hi All,

Do we have any documentation for configuring data hub. Right now i am seeing two flow one is in marklogic data-hub and other is created by quick start and both have different structure .

I am running this project in eclipse .I have successfully build marklogic data hub as i am able to see marklogic structure like database,forest, app server in mark logic using gradle build command even thouugh some test case fail .After that i have executed  quick start code   using bootRun command  .i am able to see screen and initialize server.

Now i want to execute individual commands like Re index database   or mlDelpoy. In which directory i need to do my database changes and which command i need to execute so that it will be reflected in database.

Thanks,
Vikas Singh

**Comment by dmcassel** [comment]
Vikas, please take a look at https://marklogic-community.github.io/marklogic-data-hub/understanding/project-structure/. To make database changes, you'll work inside the user-config directory. Note that you'll create the files you want to work with in that directory. 

To make a change to the final database, for instance, create `user-config/databases/final-database.json`. You can look at `hub-internal-config/databases/final-database.json` to see what properties you can add, but *do not edit anything under hub-internal-config*. It may be overwritten when you upgrade to a new version of the DHF. 

Files under hub-internal-config and user-config will be merged by gradle. The `mlDeployDatabases` gradle task will deploy your database changes. 

Please let me know if this answers your question.

**Comment by paxtonhare** [comment]
@Vikas1234 it sounds like you are running the DHF from source code. It's meant to be run as a binary unless you are contributing to the codebase or you are adding enhancements that we haven't had time to roll into the main codebase.

Do you need to run from source?

**Comment by Vikas1234** [comment]
I am evaluating dhf . 

Thanks @dmcassel  @paxtonhare  for your reply.
