### ISSUE TITLE
double parent XML elements created when serializing complex type 

### ISSUE THREAD

**Issue by gduplantier** [marklogic-community/marklogic-data-hub#619]
When modeling an Entity that includes a complex type, i.e.  another Entity, then generating Javascript code that creates the instance mapping, I would expect the serialized XML to look like the following:

    <instance>
      <EntityName>
        <complexType>
          <complexTypeProperty1/>
        </complexType>
      </EntityName>
    </instance>

Instead I'm getting the following (double elements):

    <instance>
      <EntityName>
        <complexType>
          <complexType>
            <complexTypeProperty1/>
          </complexType>
        </complexType>
      </EntityName>
    </instance>

The extract instance code in Javascript would look something similar to below:

    return {
        '$attachments': attachments,
        '$type': 'FacilityEquipment',
        '$version': '0.0.1',
        'complexType': extractInstanceComplexType(source),
      }

You can test this by creating two entities and including one in the other using a 1:1 relationship.  Generate JavaScript Code and XML format for a Harmonization flow. Update the code so that it adds the entity to the instance.

#### Tech details

Using Data-Hub framework 2.0.2.
Using Javascript with XML
MarkLogic v9.0-3
Linux CentOS 7 & Mac OSX
Harmonize run from QuickStart

**Comment by gduplantier** [comment]
Work Around:
Call instance-to-canonical-xml manually with the added xpath, "/node()" for the case when adding an embedded object. This should only add the child nodes and not the duplicate parent. I assume a similar change could be made in the DHF code.
`case json:object+
                    return
                        for $prop in $instance-property
                        return element { $key } { hu:instance-to-canonical-xml($prop)/node() }`

**Comment by grechaw** [comment]
This structure is by design.  Your modification will work but it will break the automatic transform to JSON objects.  The rationale for the repeated element is to provide consistent representation of a property whether it has scalar values or complex ones.

We do have a plan simply to provide more flexibiilty in serialization strategies, but that's an enhancement, not a bugfix.

**Comment by popzip** [comment]
This is an Entity Services, not Data Hub Framework, issue / design choice. Related to <https://github.com/marklogic/entity-services/issues/266>. Will take a look at the gap between the entity as it’s modeled and as it appears in the database. This is something that will be important to the overall model-driven approach. Please add comments about expectations / desired behavior there.
