### ISSUE TITLE
Update Spring Batch example to version 1.4.0

### ISSUE THREAD

**Issue by sastafford** [marklogic-community/marklogic-data-hub#622]
1. The issue

Want to update the Data Hub example using Spring Batch to marklogic spring batch version 1.4.0.  May need to update the DataHubItemWriter.

┆Status: New

**Comment by dmcassel** [comment]
➤ Scott Stafford commented:

I submitted a pull request for this back in December 2017.  

[https://github.com/marklogic-community/marklogic-data-hub/pull/625](https://github.com/marklogic-community/marklogic-data-hub/pull/625)

**Comment by dmcassel** [comment]
➤ Scott Stafford commented:

Do I have any action on this issue?

**Comment by dmcassel** [comment]
➤ Alexander Ebadirad commented:

We've made some changes - could you please rebase on develop, so we can pull it in without the merge conflict?

**Comment by aebadirad** [comment]
This was completed.
