### ISSUE TITLE
dhf.makeEnvelope does not include $version and $type

### ISSUE THREAD

**Issue by ltnd** [marklogic-community/marklogic-data-hub#626]
During an harmonize Flow in JSON, the $version and $type json properties are not included in the final envelope written into Final database.

**Comment by ltnd** [comment]
same to https://github.com/marklogic-community/marklogic-data-hub/issues/455

**Comment by popzip** [comment]
@ltnd if this is same as 455 does that mea nit is fixed/can close this?

**Comment by ltnd** [comment]
@popzip No, I have this issue with 2.0.2 while #455 has been fixed in 2.0.0

**Comment by paxtonhare** [comment]
this is still fixed. For whatever reason this code didn't land in 2.0.2. It's in develop and will land in 2.0.3
