### ISSUE TITLE
Clarify docs: REST resources can be added without being connected to an entity

### ISSUE THREAD

**Issue by dmcassel** [marklogic-community/marklogic-data-hub#629]
The [Project Structure page](https://marklogic-community.github.io/marklogic-data-hub/understanding/project-structure/) shows REST directories under plugins/entities/{entity}/[input|harmonize]/REST. The "plugins folder" section of that page shows a path of plugins/entities/input/REST. Apparently both work. 

- Update folder diagram to show that DHF supports REST resources not connected to an entity
- Clarify the plugins/entities section to make clear that it refers to plugins/entities/ and plugins/entities/{entity}/

**Comment by dmcassel** [comment]
In the DHF, REST resources are intended to be associated with entities. The docs will be updated to show that use. REST resources not associated with an entity is accidental; we won't take that out.

**Comment by popzip** [comment]
I believe this was completed.
