### ISSUE TITLE
Allow me to set custom SSL Context and Hostname verifiers 

### ISSUE THREAD

**Issue by mikrovvelle** [marklogic-community/marklogic-data-hub#647]
#### The issue

Need to see TLS v1.2 for App Servers, but there's no way to set TLS context in DHF.

**Comment by paxtonhare** [comment]
Right now the variables one needs to set are made private. We need setters/getters for those variables and an e2e test against TLS v1.2

**Comment by aebadirad** [comment]
This has been added and released in 2.0.3
