### ISSUE TITLE
Need ability to specify cluster hostnames in configuration, override automatic host detection

### ISSUE THREAD

**Issue by mikrovvelle** [marklogic-community/marklogic-data-hub#662]
We need a way to specify the list of hosts belonging to the cluster, instead of trusting the list of hosts reported by one of the MarkLogic servers.

#### The issue

The `hubRunFlow` task includes the following process (for harmonization):

1. Query the configured host to get the hostnames for all other cluster members.
2. Connect with the cluster members directly for task parallelization, using those hostnames.

But, there's no guarantee that those hostnames will be reachable for the gradle process running the task. A cluster can be configured so that the hostnames as (ML sees them) are not reachable from clients outside the cluster—or if the internally configured hostnames rely on a different name-resolution than that used externally.

If this is the case, the `hubRunFlow` harmonization task will fail when it tries to connect to the other hosts on the cluster.

One solution would be to add custom entries to the OS `/etc/hosts` file, but this is likely to be outside of the control of the user, especially in enterprise environments. It would be better if the list could be passed as a configuration parameter.

#### Tech details

This requires a cluster with the configuration details described above.

> Which Operating System are you using?

any

> Which version of MarkLogic are you using?

9.0-3.1

> Which version of the Data Hub Framework are you using?

2.0.2

> Is this a QuickStart UI bug? If so, which browser are you using?

not a UI bug

Edit: added that this problem was uncovered while trying to run harmonization. It may or may not also be a problem for ingest.

**Comment by damonfeldman** [comment]
Looks like we may solve this in code by exposing the whitelist capability in the Java API via ML-DHF

from "lists":


```
Working with a Load
Balancer<https://docs.marklogic.com/guide/java/data-movement#id_26583>
By default, a job tries to connect directly to multiple hosts in your cluster in
order to efficiently distribute work. However, if there is a load balancer
sitting between your client application and your MarkLogic cluster, these direct
connections may not be possible.
In this case, you can use code such as the following to restrict a job to a
specific host:
// Assume "dmm" is a previously created DataMovementManager object.
batcher.withForestConfig(
  new FilteredForestConfiguration(
    dmm.readForestConfig()
  ).withWhiteList(loadBalancerHost)
);
```

**Comment by sammefford** [comment]
@paxtonhare yes

**Comment by mikrovvelle** [comment]
I've tested this, and it indeed allows the `hubRunFlow` command to complete without errors. So the most important thing is fixed. However, it looks like this still doesn't distribute the jobs to all the cluster members. From what I can tell, it only sends tasks to the intersect of two lists:

[hosts in the configured whitelist] ⋂ [hosts reported from the cluster]

In the environment that exposed the bug, [hosts reported from the cluster] includes:

- the configured `mlHostname`, plus 
- several hostnames unreachable for the gradle process—ones only reachable from other MarkLogic hosts.

So the intersect of the two lists is actually just the one configured `mlHostname`.

Ideally, the cluster hosts used would just be [hosts in the configured whitelist], since there's no way to get these hostnames by asking MarkLogic anyway. But maybe that's a new feature or optimization. What's implemented now at least gets the job done.

**Comment by sammefford** [comment]
FilteredForestConfiguration also allows renaming hosts.  Perhaps this is what's needed?

**Comment by sammefford** [comment]
Also, ForestConfiguration is an interface specifically so you can implement your own.  FilteredForestConfiguration is just an example of what's possible.
