### ISSUE TITLE
Quickstart doesn't have "Delimited Text Options" anymore, the documentation and tutorial should be changed

### ISSUE THREAD

**Issue by ayuwono** [marklogic-community/marklogic-data-hub#683]
Quickstart doesn't have "Delimited Text Options" anymore, the documentation and tutorial should be changed

https://marklogic-community.github.io/marklogic-data-hub/tutorial/load-products-as-is/

**Comment by popzip** [comment]
@paxtonhare when did this go away/what changed

**Comment by aebadirad** [comment]
<img width="434" alt="text" src="https://user-images.githubusercontent.com/2173410/35403760-fdf3fbdc-01bd-11e8-80e0-b23e9d78e622.png">

I still see it as present in the develop branch

**Comment by ayuwono** [comment]
I meant the Delimited Text Options on the bottom page. The one that you can enable "Generate URI?" option.

This is a screenshot from recent develop branch (no Delimited Text Options, it seems that it got changed by Flow Options?):
<img width="1388" alt="screen shot 2018-01-25 at 10 16 57 am" src="https://user-images.githubusercontent.com/7096668/35404864-3af4f64e-01b9-11e8-8a25-75635aef29d9.png">

This is the tutorial page that shows Delimited Text Options:
<img width="1107" alt="screen shot 2018-01-25 at 10 16 42 am" src="https://user-images.githubusercontent.com/7096668/35404880-4836512c-01b9-11e8-9e61-abaaadf82581.png">

**Comment by dmcassel** [comment]
I think the Delimited Text Options only show up if you have specified Input File Type -> Delimited Text. In your screenshot, the MLCP command is showing that the document type is JSON. Please change to Delimited Text and see whether those options appear.

**Comment by ayuwono** [comment]
I specified Input File Type to "Delimited Text" and even changed the document type to "json", but I still don't see the Delimited Text Options

Selected "Delimited Text"
<img width="1166" alt="screen shot 2018-01-26 at 10 22 50 am" src="https://user-images.githubusercontent.com/7096668/35454679-d8d9e58e-0283-11e8-8878-9b4c59feba72.png">

Still no "Delimited Text Options"
<img width="1131" alt="screen shot 2018-01-26 at 10 27 09 am" src="https://user-images.githubusercontent.com/7096668/35454698-ee6d368a-0283-11e8-87ae-8ecce560e792.png">

**Comment by ayuwono** [comment]
By the way, according the tutorial, the document type should still be json. The input file type is changed to delimited text

**Comment by aebadirad** [comment]
This should be fixed in: https://github.com/marklogic-community/marklogic-data-hub/pull/695

**Comment by aebadirad** [comment]
Merged into dev.
