### ISSUE TITLE
QuickStart harmonize flow settings not persisted during browser session

### ISSUE THREAD

**Issue by wooldridge** [marklogic-community/marklogic-data-hub#684]
In the harmonize flow settings (which includes batch size and thread count), the values are not persisted when I change the values, leave that page view, and then return. The settings go back to the defaults.

To reproduce:

1. In the Flows view, create a harmonize flow ("harmonize 1") with defaults (batch size = 100, thread count = 4).
2. Change the settings (batch size = 50, thread count = 2).
3. Click "Dashboard" to change the page view, then click "Flows" to return to the Flows view.
4. Select the flow you created in step 1. 
5. The flow settings are back to their defaults (batch size = 100, thread count = 4).

Furthermore, if I have multiple harmonize flows defined, I can't define separate flow settings for the different harmonize flows. Only one set of settings is maintained.

To reproduce:

1. In the Flows view, create two harmonize flows ("harmonize 1", "harmonize 2") with defaults (batch size = 100, thread count = 4).
2. Change the settings for one of the flows, "harmonize 1" (batch size = 50, thread count = 2).
3. Click "harmonize 2" to switch to the other flow.
4. The second flow has the non-default settings  (batch size = 50, thread count = 2).
5. Manually change the settings for the second flow (batch size = 80, thread count = 6).
6. Click "harmonize 1" to switch back to the first flow. The flow settings remain the same (batch size = 80, thread count = 6), they don't return to what we defined in step 2.

I would expect the settings associated with a harmonize flow to be independent of the other flows and to persist as I use other parts of the application.

#### Tech details

Which Operating System are you using? Mac OS

Which version of MarkLogic are you using? trunk

Which version of the Data Hub Framework are you using? develop branch

Is this a QuickStart UI bug? If so, which browser are you using? Chrome

**Comment by wooldridge** [comment]
I am addressing this as part of my work on DHFPROD-167:

https://github.com/wooldridge/marklogic-data-hub/tree/DHFPROD-167

**Comment by ayuwono** [comment]
Hi @wooldridge 

The persistency works, but there is a bug on deleting the options, it seems that it's persistent
1. Create a harmonize flow and a key-value option
2. Delete the option created on step 1
3. Go to the other tab or the other harmonize flow
4. Go back to the harmonize flow created on step 1

The deleted option is displayed again.  It should be deleted

**Comment by wooldridge** [comment]
@ayuwono, I've updated the branch to delete removed options from local storage. The issue you described should be fixed.

https://github.com/wooldridge/marklogic-data-hub/tree/DHFPROD-167

**Comment by popzip** [comment]
@wooldridge whats the status of this bug - is it a blocker for #504 ?

**Comment by wooldridge** [comment]
@popzip this bug is fixed and can be closed.
