### ISSUE TITLE
Setting up QuickStart UI takes me to the update screen, then vicious cycle

### ISSUE THREAD

**Issue by wooldridge** [marklogic-community/marklogic-data-hub#698]
Can't complete QuickStart UI setup in the browser (develop branch with ML9). Eventually takes me to the update screen that leads to a vicious cycle.

#### Steps to Reproduce

1. Run bootRun and runUI in separate terminals.

2. With a clean MarkLogic (new data directory) and clean data-hub project folder, go through installation process starting at: http://localhost:4200/

3. Reach "Installation into MarkLogic is complete!" screen. Here, clicking the "FINISHED" button on this screen does nothing. 

Seeing an error in the browser console, don't know if this is relevant:

{"percentComplete":100,"message":"java.lang.RuntimeException: com.marklogic.client.FailedRequestException: Local message: config/resources write failed: Bad Request. Server Message: RESTAPI-INVALIDCONTENT: (err:FOER0000) Invalid content: invalid search-options-generator extension: could not parse XQuery extension search-options-generator; please see the server error log for detail XDMP-MODNOTFOUND: (err:XQST0059) Module /MarkLogic/entity-services/entity-services.xqy not found; search-options-generator either is not a valid module or does not provide extension functions (delete, get, put, post) in the http://marklogic.com/rest-api/resource/search-options-generator namespace\n\tat com.marklogic.hub.deploy.commands.LoadHubModulesCommand.execute(LoadHubModulesCommand.java:90)\n\tat com.marklogic.hub.deploy.HubAppDeployer.deploy(HubAppDeployer.java:58)\n\tat com.marklogic.hub.DataHub.install(DataHub.java:306)\n\tat 

4. Open http://localhost:4200/

5. Go through initial screens again until, after username/password screen, I land on "Congratulations on updating to version 2.0.2" screen. Click the only button available, "UPDATE IT".

The app works for a while and takes me back to the "Congratulations on updating to version 2.0.2" screen. 

@ayuwono is experiencing this, too.

#### Tech details

Which Operating System are you using? Mac OS

Which version of MarkLogic are you using? MarkLogic 9.0-20180129

Which version of the Data Hub Framework are you using? develop branch

Is this a QuickStart UI bug? If so, which browser are you using? Chrome

**Comment by aebadirad** [comment]
This should be fixed in dev now with the last merge

**Comment by aebadirad** [comment]
Fixed in 2.0.3, closing issue
