### ISSUE TITLE
problem with instance-json-from document when extracting array of string

### ISSUE THREAD

**Issue by joecrean** [marklogic-community/marklogic-data-hub#708]
@grechaw 

### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

I have a property defined as an array of string as follows
```
"keyword" : {
          "datatype" : "array",
          "items" : {
            "datatype" : "string",
            "collation" : "http://marklogic.com/collation/codepoint"
          }
        },
```
although my content is xml, i need to return the search results in json and have written a transform to return the asset instance in json. I use the function es:instance-json-from-document(). I noticed that in the array type, the second value in the array is always replaced by a null.
```
                       "keyword": [
                            "Cell Line",
                            null,
                            "DNA",
                            "DNA, Recombinant",
                            "Genes",
                            "Globins",
                            "Microscopy, Electron",
                            "Molecular Weight",
                            "Nucleic Acid Hybridization",
                            "Nucleic Acid Precursors",
                            "RNA, Messenger"
                        ],
```
What behavior are you expecting? the second value is always missing and is replaced by a null.

#### Tech details

Which Operating System are you using? windows, linux
 
Which version of MarkLogic are you using? 9-03

Which version of the Data Hub Framework are you using? 2.0.2

Is this a QuickStart UI bug? If so, which browser are you using?

Suggested solution:
I have debugged this down to ``entity-services/entity-services-instance.xqy`` and the function ``inst:child-instance``. When we find we are processing an element for a second time we convert it to an array as in the following else branch

```
            else 
                        let $_ := xdmp:log("XX convert to array here 2")
                        let $new-array := json:array()
                        return (
                            json:array-push($new-array, map:get($child, local-name($property))),
                            json:array-push($new-array, local:child-instance($property/*) ),
                            map:put($child, local-name($property), $new-array)
                        )
```
we call the same function to process property children whereas we should test it first to see if there is an element chld , if not just get its value. This approach is taken in the if-then branch of the same if clause. The fix is as follows and works on my tests.

```
            else 
                        let $_ := xdmp:log("XX convert to array here 2")
                        let $new-array := json:array()
                        return (
                            json:array-push($new-array, map:get($child, local-name($property))),
                            json:array-push($new-array, 
if ($property/element())
                            then local:child-instance($property/*) 
                            else data($property),,
                            map:put($child, local-name($property), $new-array)
                        )
```

**Comment by grechaw** [comment]
Thanks for this bug report @joecrean , well reported.  I'll open an entity services issue pointing to this one.  Unfortunately, 9.0-4 just went out the door, so it's a while til 9.0-5.

**Comment by grechaw** [comment]
https://github.com/marklogic/entity-services/issues/364

**Comment by popzip** [comment]
@grechaw so, no fix to make in DHF code, just surfaced in the hub but is something underlying Entity Services? Or will there be a DHF fix to make as well?

**Comment by dmcassel** [comment]
waiting on the entity services fix
