### ISSUE TITLE
Missing custom webservices in DHF

### ISSUE THREAD

**Issue by tomaszs86** [marklogic-community/marklogic-data-hub#716]
DHF - 2.0.2 / 2.0.3
MarkLogic - 9.0-3.1
Configuration: localhost, digest authentication without ssl (default)

I've generated custom webservice called x in DHF project using mlCreateResource. I've deployed app, but there is no x webservice in module database. DHF has deployed default framework webservices (delete-jobs, entity, flow, hubstats, hubversion) but haven't deployed my custom webservice.

How to fix it?

**Comment by paxtonhare** [comment]
@tomaszs86 where did you place the mlCreateResource file?

According to 
https://marklogic-community.github.io/marklogic-data-hub/understanding/project-structure/

You should put it in either:

`plugins/entities/{entity}/input/REST/services`

or

`plugins/entities/{entity}/harmonize/REST/services`

**Comment by tomaszs86** [comment]
ok, thanks
