### ISSUE TITLE
Browse Data Entities Only Error

### ISSUE THREAD

**Issue by bobstarbird** [marklogic-community/marklogic-data-hub#726]
Short description of the problem:

After upgrading Browse Date->Entities Only returns an error

Which version of MarkLogic are you using?
9.0-2

Which version of the Data Hub Framework are you using?
2.0.3

I just upgraded from 2.0.0 to 2.0.3
 
Clicking on Browse Data and then Entities Only I got an error:
 
`16:09:32.276 [http-nio-8080-exec-2] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.marklogic.client.FailedRequestException: Local message: search failed: Bad Request. Server Message: XDMP-LEXVAL: cts:qname("*:instance") -- Invalid lexical value "*:instance"] with root cause
com.marklogic.client.FailedRequestException: Local message: search failed: Bad Request. Server Message: XDMP-LEXVAL: cts:qname("*:instance") -- Invalid lexical value "*:instance"`

WORKAROUND:
Modified options files under $dir/entity-config
"staging-entity-options.xml" and "final-entity-options.xml" to change from
`   <search:additional-query>
    <cts:element-query xmlns:cts="http://marklogic.com/cts">
      <cts:element>*:instance</cts:element>
      <cts:true-query/>
    </cts:element-query>
  </search:additional-query>`

to be

`  <search:additional-query>
    <cts:element-query xmlns:cts="http://marklogic.com/cts">
      <cts:element>instance</cts:element>
      <cts:true-query/>
    </cts:element-query>
  </search:additional-query>`

**Comment by aebadirad** [comment]
Bug confirmed. Need to modify how we generate options file.
