### ISSUE TITLE
Install screen on quickstart is broken, unable to install hub [blocker]

### ISSUE THREAD

**Issue by ayuwono** [marklogic-community/marklogic-data-hub#778]
1) Create a new project by choosing a new directory
2) Click next until it's prompted to login
3) After the login, there is no install page, the page is broken as the screenshot below

![](https://user-images.githubusercontent.com/7096668/37011129-903add9a-20a3-11e8-9641-bafc32a8a5dc.png)

This is a blocker

#### Tech details
Which Operating System are you using? Mac OSX

Which version of MarkLogic are you using? 9.0-nightly

Which version of the Data Hub Framework are you using? 2.0.4

Is this a QuickStart UI bug? If so, which browser are you using? Yes, Chrome

┆Status: To Do

**Comment by paxtonhare** [comment]
@ayuwono can you see if there are any errors in the JS console? Or in the Java console window from the cmd line?

**Comment by dmcassel** [comment]
Is this actually using 2.0.4 or is it using the latest code in the dev branch?

**Comment by ayuwono** [comment]
Yes, just tested on develop, it's fixed now. Installation of hub is working fine

**Comment by ayuwono** [comment]
It happens on develop, not 2.0.4
