### ISSUE TITLE
Reverse DB EndToEndFlowTests fail on AWS

### ISSUE THREAD

**Issue by srinathgit** [marklogic-community/marklogic-data-hub#800]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:
Harmonize flows with staging and final DBs reversed fails on AWS. The host name is the primary host of the ML cluster on AWS.

#### Tech details

Which Operating System are you using?
AWS Linux instance

Which version of MarkLogic are you using?
MarkLogic nightly server (9.0-20180227)

Which version of the Data Hub Framework are you using?
Develop code as of 03/08/18

Is this a QuickStart UI bug? If so, which browser are you using?
NO
#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

┆Status: New

**Comment by popzip** [comment]
Now running on AWS, check on whether need to test on load balancer.
