### ISSUE TITLE
Create concept of a domain

### ISSUE THREAD

**Issue by paxtonhare** [marklogic-community/marklogic-data-hub#82]
A domain would be useful for organizing entities.
### Health Insurance (domain)
- claims (entity)
- patients (entity)
### Sales Operations (domain)
- orders
- products
- customers

This depends on #53 being completed first. This if a future task based on people's feedback.

**Comment by jmakeig** [comment]
@paxtonhare Is this just hierarchy in the entity list to logically group entities or something bigger?

**Comment by grechaw** [comment]
To me, this idea can be expressed in one of two places.
It might be like a MarkLogic collection, a tag to identify entities that belong together.
Or it could be like a container, which groups together Entity Types into a coherent whole.  In this case it's analogous to the Entity Services Model, but without the current idea that a Model has to contain all of its referents. 

We might need both concepts.  The first can be implemented just as a property (array of refs) to identifiers of Domains.  The second could be accomplished in the 9.0-2 timeframe I'd hope by implementing a design for dynamically creating Models from triples.  I've implemented how to query entity types from a bag of triples, but we need to think about what the `/info` section is all about for dynamically-created models.
