### ISSUE TITLE
Error when trying to run mlDeploy from online store example on development branch

### ISSUE THREAD

**Issue by mhuang-ml** [marklogic-community/marklogic-data-hub#835]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:
If I run mlDeploy from the development branch for the "online-store" example, then I receive an error message that prevents the project from deploying.  I have the same error message being thrown when I try running gradle runui as well, but I wanted to isolate this to a working example as well.

What behavior are you expecting?
I should be able to run mlDeploy and the project should be deployed without any issues.

#### Tech details

Which Operating System are you using?
Mac OSX 10.12.6
Which version of MarkLogic are you using?
9.0-3.1
Which version of the Data Hub Framework are you using?
Latest from the 2.0 development branch
Is this a QuickStart UI bug? If so, which browser are you using?
No
#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:
The full output from `gradle mlDeploy --debug` is attached
[deployOutput.txt](https://github.com/marklogic-community/marklogic-data-hub/files/1843698/deployOutput.txt)

┆Status: New

**Comment by mhuang-ml** [comment]
When I opened this bug, then I was tracking from the development branch, which requires the nightly build to run properly.  I created a new VM with the ML nightly and I can confirm that with the develop branch and the ML nightly, then there is **NO** issue.

**Comment by dmcassel** [comment]
➤ Michael Huang commented:

This bug can be CLOSED since it is NOT an issue once I installed a ML nightly build.  I don't see the ability to close this bug on my own.
