### ISSUE TITLE
gradlew quick-start:e2eLaunch could not find or load main class com.marklogic.quickstart.Application

### ISSUE THREAD

**Issue by ayuwono** [marklogic-community/marklogic-data-hub#877]
gradlew quick-start:e2eLaunch command has an error to load main class. This is blocking QA to run e2e tests. It happens locally and on jenkins env. Branch: develop and 3.x-develop

Command:
+ ./gradlew quick-start:e2eLaunch
:quick-start:cleanUI UP-TO-DATE
:quick-start:nodeSetup
:quick-start:npmInstallUI
:quick-start:buildUI
:quick-start:startRest
:quick-start:e2eLaunch

Error: Could not find or load main class com.marklogic.quickstart.Application

[HPM] Error occurred while trying to proxy request /api/projects/ from localhost:49152 to http://localhost:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

┆Status: New

**Comment by ayuwono** [comment]
Before the refactor, we used to run e2e by using this command quick-start:test and it would run the e2e tests on the first part then it would run the junit tests. It seems that running the same command right now will run the junit tests first.

**Comment by ayuwono** [comment]
The could not find class error is happening on quick-start:buildUI task:

```
> Task :quick-start:buildUI 

> data-hub-quickstart@3.0.0 build.prod /Users/ayuwono/builds/macosx-64/b9_0/marklogic-data-hub-dev/quick-start
> npm run clean.dist && ng build -prod


> data-hub-quickstart@3.0.0 clean.dist /Users/ayuwono/builds/macosx-64/b9_0/marklogic-data-hub-dev/quick-start
> npm run rimraf -- dist


> data-hub-quickstart@3.0.0 rimraf /Users/ayuwono/builds/macosx-64/b9_0/marklogic-data-hub-dev/quick-start
> rimraf "dist"

Warning: Can't resolve all parameters for TooltipOptions in /Users/ayuwono/builds/macosx-64/b9_0/marklogic-data-hub-dev/quick-start/src/main/ui/app/tooltip/tooltip-options.class.ts: (?). This will become an error in Angular v5.x
Warning: Can't resolve all parameters for TooltipOptions in /Users/ayuwono/builds/macosx-64/b9_0/marklogic-data-hub-dev/quick-start/src/main/ui/app/tooltip/tooltip-options.class.ts: (?). This will become an error in Angular v5.x
Warning: Can't resolve all parameters for HubRequestOptions in /Users/ayuwono/builds/macosx-64/b9_0/marklogic-data-hub-dev/quick-start/src/main/ui/app/auth/request-options.ts: (?). This will become an error in Angular v5.x
Warning: Can't resolve all parameters for HubRequestOptions in /Users/ayuwono/builds/macosx-64/b9_0/marklogic-data-hub-dev/quick-start/src/main/ui/app/auth/request-options.ts: (?). This will become an error in Angular v5.x
Date: 2018-04-11T17:07:22.602Z[59s]
Hash: ecfb78cb52a0bd8a472e
Time: 40607ms
chunk {0} polyfills.6560706e5617260ec205.bundle.js (polyfills) 103 kB [initial] [rendered]
chunk {1} main.6229a0e7fb0c91741ef9.bundle.js (main) 9.33 MB [initial] [rendered]
chunk {
Error: Could not find or load main class com.marklogic.quickstart.Application
```

**Comment by grechaw** [comment]
I was able to reproduce by cleaning first.
workaround is to run gradle compileJava first, but I've also got a fix.

So when kiran removed the dependency on java tests, it also removed the depenency on the compilation of the main project.

**Comment by grechaw** [comment]
pushed a fix to my currenly open PR

**Comment by dmcassel** [comment]
➤ Aries Yuwono commented:

Confirmed, running gradle compileJava first then e2eLaunch works

**Comment by grechaw** [comment]
This is all set to go, Aries.

**Comment by ayuwono** [comment]
e2eLaunch is working fine now
